PKG_NAME = zope.event
PKG_VERS = 4.5.0
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = https://files.pythonhosted.org/packages/source/z/${PKG_NAME}
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

HOMEPAGE = https://github.com/zopefoundation/zope.event
COMMENT  = Very basic event publishing system
LICENSE  = Zope Public License (ZPL 2.1)

include ../../mk/spksrc.python-wheel.mk
