SPK_NAME = jdupes
SPK_VERS = 1.51
SPK_REV = 2
SPK_ICON = src/jdupes.png

DEPENDS = cross/jdupes

MAINTAINER = jbruchon
DESCRIPTION = A powerful duplicate file finder and an enhanced fork of fdupes
DISPLAY_NAME = jdupes
STARTABLE = no
BETA = 1

HOMEPAGE   = https://github.com/jbruchon/jdupes/
LICENSE    = MIT
HELP_URL   = https://github.com/jbruchon/jdupes/README

INSTALLER_SCRIPT = src/installer.sh
SSS_SCRIPT       = src/dsm-control.sh

INSTALL_PREFIX = /usr/local/$(SPK_NAME)

include ../../mk/spksrc.spk.mk
