SPK_NAME = imapfilter
SPK_VERS = 2.6.16
SPK_REV = 1

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = VanStratum
DESCRIPTION = An IMAP mail filtering utility using the Lua programming language as a configuration and extension language.
STARTABLE = no
DISPLAY_NAME = Imapfilter

HOMEPAGE = http://github.com/lefcha/imapfilter
LICENSE  = MIT

INSTALL_PREFIX = /usr/local

SERVICE_SETUP = src/service-setup.sh

include ../../mk/spksrc.spk.mk
