SPK_NAME = imapfilter
SPK_VERS = 2.7.5
SPK_REV = 1

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = VanStratum
DESCRIPTION = An IMAP mail filtering utility using the Lua programming language as a configuration and extension language.
STARTABLE = no
DISPLAY_NAME = IMAPFilter

HOMEPAGE = http://github.com/lefcha/imapfilter
LICENSE  = MIT

SPK_COMMANDS = bin/imapfilter
SPK_LINKS = /usr/local/share/imapfilter:share/imapfilter

include ../../mk/spksrc.spk.mk
