SPK_NAME = imapfilter
SPK_VERS = 2.8.3
SPK_REV = 1

DEPENDS = cross/imapfilter

MAINTAINER = VanStratum
DESCRIPTION = An IMAP mail filtering utility using the Lua programming language as a configuration and extension language.
STARTABLE = no
DISPLAY_NAME = IMAPFilter

HOMEPAGE = http://github.com/lefcha/imapfilter
LICENSE  = MIT

SPK_COMMANDS = bin/imapfilter

include ../../mk/spksrc.spk.mk
