PKG_NAME = libatomic_ops
PKG_VERS = 7.4.0
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = http://www.ivmaisoft.com/atomic_ops/download/
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

HOMEPAGE = https://github.com/ivmai/libatomic_ops/
COMMENT  = Atomic memory update operations portable implementation
LICENSE  = https://github.com/ivmai/libatomic_ops/blob/master/doc/LICENSING.txt

GNU_CONFIGURE = 1

include ../../mk/spksrc.cross-cc.mk
