SPK_NAME = lua
SPK_VERS = 5.4.7
SPK_REV = 5
SPK_ICON = src/lua.png

DEPENDS = cross/lua

MAINTAINER = eelcohn
MAINTAINER_URL = https://www.lua.org/
HELPURL = https://www.lua.org/start.html

DESCRIPTION = Lua is a powerful, efficient, lightweight, embeddable scripting language. It supports procedural programming, object-oriented programming, functional programming, data-driven programming, and data description.
DISPLAY_NAME = Lua
STARTABLE = no
CHANGELOG = "Update lua to v5.4.7"

HOMEPAGE = https://www.lua.org
LICENSE = MIT

SPK_COMMANDS = bin/lua bin/luac

include ../../mk/spksrc.spk.mk
