TC_ARCH = rtd1296
TC_VERS = 6.2.2
TC_KERNEL = 4.4.59+

TC_DIST = rtd1296-gcc494_glibc220_armv8-GPL
TC_DIST_SITE = https://sourceforge.net/projects/dsgpl/files/Tool%20Chain/DSM%206.2.2%20Tool%20Chains/Realtek%20RTD129x%20Linux%204.4.59

TC_PREFIX = aarch64-unknown-linux-gnueabi
TC_SYSROOT = $(TC_PREFIX)/sysroot

include ../../mk/spksrc.tc.mk
