TC_ARCH = bromolow
TC_VERS = 5.0

TC_DIST = gcc473_glibc217_x86_64_bromolow-GPL
TC_EXT = tgz
TC_DIST_SITE = https://sourceforge.net/projects/dsgpl/files/Tool%20Chain/DSM%205.0%20Tool%20Chains/Intel%20x86%20Linux%203.2.40%20%28Bromolow%29

TC_PREFIX = x86_64-pc-linux-gnu
TC_SYSROOT = $(TC_PREFIX)/sys-root

include ../../mk/spksrc.tc.mk
