SPK_NAME = less
SPK_VERS = 668
SPK_REV = 1
SPK_ICON = src/gnu-logo.png

DEPENDS = cross/less

MAINTAINER = SynoCommunity
DESCRIPTION = Less is a terminal pager.
DISPLAY_NAME = Less
STARTABLE = no

HOMEPAGE = https://www.gnu.org/software/less/
LICENSE = GPLv3

SPK_COMMANDS = bin/less bin/lessecho bin/lesskey

include ../../mk/spksrc.spk.mk
