TC_NAME = syno-armv7

# generic toolchain for arm7hf SRM
TC_ARCH = northstarplus ipq806x dakota
TC_VERS = 1.2
TC_TYPE = SRM
TC_KERNEL = 4.4.60
TC_GCC = 4.9.3
TC_GLIBC = 2.20

TC_DIST = gcc493_glibc220_hard-GPL
TC_EXT = tgz
TC_DIST_SITE_PATH = QUALCOMM%20IPQ806X%20Linux%204.4.60
TC_DIST_FILE = ipq806x-$(TC_DIST_NAME)

TC_TARGET = arm-unknown-linux-gnueabi
TC_SYSROOT = $(TC_TARGET)/sysroot

include ../../mk/spksrc.tc.mk
