SPK_NAME = bat
SPK_VERS = 0.21.0
SPK_REV = 1

DEPENDS = cross/$(SPK_NAME)

UNSUPPORTED_ARCHS = $(OLD_PPC_ARCHS) $(ARMv5_ARCHS)

MAINTAINER = SynoCommunity
DESCRIPTION = A cat(1) clone with wings.
STARTABLE = no

HOMEPAGE = https://github.com/sharkdp/bat
LICENSE  = MIT or Apache 2.0

SPK_COMMANDS = bin/bat

include ../../mk/spksrc.spk.mk
