SPK_NAME = nano
SPK_VERS = 2.5.1
SPK_REV = 2
SPK_ICON = src/nano.png

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = SynoCommunity
DESCRIPTION = nano is a text editor for Unix-like computing systems or operating environments using a command line interface.
DESCRIPTION_GER = nano ist ein einfacher Editor, der die Bearbeitung von Dateien in einem Terminal bzw. auf der Konsole erlaubt.
RELOAD_UI = no
DISPLAY_NAME = nano
STARTABLE = no
CHANGELOG = "Update to 2.5.1<br>2. Remove beta tag"

HOMEPAGE   = http://www.nano-editor.org
LICENSE    = GPLv2

INSTALLER_SCRIPT = src/installer.sh
SSS_SCRIPT       = src/dsm-control.sh

INSTALL_PREFIX = /usr/local/$(SPK_NAME)

include ../../mk/spksrc.spk.mk
