PKG_NAME = tiff
PKG_VERS = 4.0.6
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = ftp://ftp.remotesensing.org/pub/libtiff
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS =

HOMEPAGE = http://www.remotesensing.org/libtiff/
COMMENT  = LibTIFF provides support for the Tag Image File Format (TIFF), a widely used format for storing image data.
LICENSE  =

GNU_CONFIGURE = 1

include ../../mk/spksrc.cross-cc.mk

