
PKG_NAME = portaudio
PKG_VERS = 19_20111121
PKG_EXT = tgz
PKG_DIR = $(PKG_NAME)
PKG_DIST_NAME = pa_stable_v$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = http://www.portaudio.com/archives

DEPENDS = cross/alsa-oss

MAINTAINER=	http://packages.nas-forum.com/
HOMEPAGE=	http://www.portaudio.com/
COMMENT=	Audio I/O library
LICENSE=	http://www.portaudio.com/license.html

GNU_CONFIGURE = 1

include ../../mk/spksrc.cross-cc.mk
