SPK_NAME = synocli-misc
SPK_VERS = 1.0
SPK_REV = 1
SPK_ICON = src/synocli-misc.png

DEPENDS = cross/bc cross/moreutils

MAINTAINER = SynoCommunity
DISPLAY_NAME = SynoCli misc. Tools

DESCRIPTION = "SynoCli misc. Tools provide a set of small miscellaneous command-line utilities: bc, errno, ifdata, ifne, isutf8, lckdo, mispipe, parallel, pee, sponge."
STARTABLE = no
CHANGELOG = "Initial package release."

HOMEPAGE = https://github.com/SynoCommunity/spksrc/wiki/FAQ-SynoCliMisc
LICENSE  = Each tool is licensed under it's respective license.

# gnu:
SPK_COMMANDS = bin/bc bin/dc

# moreutils:
SPK_COMMANDS += bin/errno
SPK_COMMANDS += bin/ifdata
SPK_COMMANDS += bin/ifne
SPK_COMMANDS += bin/isutf8
SPK_COMMANDS += bin/lckdo
SPK_COMMANDS += bin/mispipe
SPK_COMMANDS += bin/parallel
SPK_COMMANDS += bin/pee
SPK_COMMANDS += bin/sponge

include ../../mk/spksrc.spk.mk
