
PATH="${SYNOPKG_PKGDEST}/bin:${PATH}"
JACKETT="${SYNOPKG_PKGDEST}/share/jackett"
HOME_DIR="${SYNOPKG_PKGDEST}/var"

SERVICE_COMMAND="env HOME=${HOME_DIR} PATH=${PATH} LD_LIBRARY_PATH=${SYNOPKG_PKGDEST}/lib ${JACKETT} --PIDFile ${PID_FILE}"
SVC_BACKGROUND=y
