PKG_NAME = six
PKG_VERS = 1.10.0
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = https://files.pythonhosted.org/packages/source/s/$(PKG_NAME)
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS =

HOMEPAGE = http://pypi.python.org/pypi/six
COMMENT  = Python 2 and 3 compatibility utilities
LICENSE  = MIT

include ../../mk/spksrc.python-module.mk
