PKG_NAME = boto
PKG_VERS = 2.38.0
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = https://files.pythonhosted.org/packages/source/b/$(PKG_NAME)
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS =

HOMEPAGE = https://github.com/boto
COMMENT  = A Python interface to Amazon Web Services
LICENSE  = MIT License

include ../../mk/spksrc.python-wheel.mk
