TC_ARCH = powerpc
TC_VERS = 4.0
TC_FIRMWARE = 3.1-1594
TC_KERNEL = 2.4.22
TC_GCC = 3.3.4
TC_GLIBC = 2.3.3

TC_DIST = gcc334_glibc233_ppc-GPL
TC_EXT = tgz
TC_DIST_SITE_PATH = PowerPC%20824x%20Linux%202.4.22

TC_TARGET = powerpc-linux
TC_SYSROOT = $(TC_TARGET)
TC_INCLUDE = $(TC_SYSROOT)/include

include ../../mk/spksrc.tc.mk
