TOOLKIT_ARCH = evansport
TOOLKIT_VERS = 5.2

TOOLKIT_EXT = tgz
TOOLKIT_DIST_SITE = https://sourceforge.net/projects/dsgpl/files/toolkit/evansport

TOOLKIT_TARGET = i686-pc-linux-gnu
TOOLKIT_PREFIX = syno
TOOLKIT_STRIP = 2
TOOLKIT_BASE_DIR = nop
TOOLKIT_SYSROOT = nop

include ../../mk/spksrc.toolkit.mk
