PKG_NAME = pcre
PKG_VERS = 8.33
PKG_EXT = tar.bz2
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = ftp://ftp.csx.cam.ac.uk/pub/software/programming/$(PKG_NAME)
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS =

HOMEPAGE = http://www.pcre.org/
COMMENT  = A library that implements Perl 5-style regular expressions
LICENSE  =

GNU_CONFIGURE = 1

include ../../mk/spksrc.cross-cc.mk
