SPK_NAME = node
SPK_VERS = 0.10.33
SPK_REV = 1
SPK_ICON = src/nodejs.png

DEPENDS  = cross/$(SPK_NAME)

MAINTAINER = SynoCommunity
DESCRIPTION = Node.js is a platform built on Chrome\'s JavaScript runtime for easily building fast, scalable network applications.
STARTABLE = no
DISPLAY_NAME = Node.js

HOMEPAGE   = http://nodejs.org/
LICENSE    = MIT

INSTALLER_SCRIPT = src/installer.sh
SSS_SCRIPT       = src/dsm-control.sh

INSTALL_PREFIX = /usr/local/$(SPK_NAME)

include ../../mk/spksrc.spk.mk

