PKG_NAME = yasm
PKG_VERS = 1.3.0
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = http://www.tortall.net/projects/yasm/releases
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS =

HOMEPAGE = http://yasm.tortall.net
COMMENT  = Yasm is a complete rewrite of the NASM assembler under the new BSD License.
LICENSE  = BSD

GNU_CONFIGURE = 1

include ../../mk/spksrc.native-cc.mk
