PKG_NAME = c-ares
PKG_VERS = 1.7.5
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = http://c-ares.haxx.se/download
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS =

HOMEPAGE = http://code.google.com/p/umurmur/
COMMENT  = Minimalistic Mumble server
LICENSE  =

GNU_CONFIGURE = 1
CONFIGURE_ARGS =

include ../../mk/spksrc.cross-cc.mk

