PKG_NAME = SimpleExtJSApp
PKG_VERS = 0.1
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = https://github.com/DigitalBox98/SimpleExtJSApp/releases/download/v0.1/
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS =

HOMEPAGE = https://github.com/DigitalBox98/
COMMENT  = ASimple ExtJS Application for DSM 7.0

include ../../mk/spksrc.cross-cc.mk
