PKG_NAME = omx-realtek

DEPENDS = cross/omx-realtek-include cross/omx-realtek-libs

HOMEPAGE = https://archive.synology.com/download
COMMENT  = Realtek OMX hardware acceleration libraries for use with ARMv8 (aarch64) Synology NAS
LICENSE  = unknown

UNSUPPORTED_ARCHS = $(PPC_ARCHS) $(ARMv5_ARCHS) $(ARMv7_ARCHS) $(ARMv7L_ARCHS) $(x64_ARCHS) $(i686_ARCHS)

DOWNLOAD_TARGET = nop
CHECKSUM_TARGET = nop
EXTRACT_TARGET = nop
CONFIGURE_TARGET = nop
COMPILE_TARGET = nop
INSTALL_TARGET = nop

include ../../mk/spksrc.install-resources.mk
