TC_ARCH = armada37xx
TC_VERS = 6.2.4
TC_KERNEL = 4.4.59
TC_GCC = 4.9.4
TC_GLIBC = 2.20

TC_DIST = armada37xx-gcc494_glibc220_armv8-GPL
TC_DIST_SITE_PATH = Marvell%20Armada%2037xx%20Linux%204.4.59

TC_TARGET = aarch64-unknown-linux-gnueabi
TC_SYSROOT = $(TC_TARGET)/sysroot

include ../../mk/spksrc.tc.mk
