TC_ARCH = armada37xx
TC_VERS = 6.2

# No toolchain available for armada37xx so use equivalent rtd1296
TC_DIST = rtd1296-gcc494_glibc220_armv8-GPL
TC_DIST_SITE_PATH = Intel%20x86%20Linux%204.4.59%20%28Rtd1296%29

TC_TARGET = aarch64-unknown-linux-gnueabi
TC_SYSROOT = $(TC_TARGET)/sysroot

include ../../mk/spksrc.tc.mk
