PKG_NAME = sqlite-autoconf
PKG_VERS = 3420000
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = https://www.sqlite.org/2023
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

HOMEPAGE = https://www.sqlite.org/
COMMENT  = Self-contained, serverless, zero-configuration, transactional SQL database engine.
LICENSE  = Public Domain

GNU_CONFIGURE = 1

include ../../mk/spksrc.native-cc.mk
