PKG_NAME = dvb-apps
PKG_VERS = 3d43b280298c
PKG_EXT = tar.bz2
PKG_DIST_NAME = $(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = http://linuxtv.org/hg/dvb-apps/archive
PKG_DIST_FILE = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS =

HOMEPAGE = https://www.linuxtv.org/wiki/index.php/LinuxTV_dvb-apps
COMMENT  = Linux DVB API applications and useful DVB utilitie
LICENSE  = GPL

CONFIGURE_TARGET = nop

include ../../mk/spksrc.cross-cc.mk
