TC_ARCH = northstarplus
TC_VERS = 1.2
TC_TYPE = SRM
TC_KERNEL = 3.6.11
TC_GCC = 4.9.3
TC_GLIBC = 2.20

TC_DIST = gcc493_glibc220_hard-GPL
TC_EXT = tgz
TC_DIST_SITE_PATH = BROADCOM%20NORTHSTARPLUS%20Linux%203.6.11
TC_DIST_FILE = $(TC_ARCH)-$(TC_DIST_NAME)

TC_TARGET = arm-unknown-linux-gnueabi
TC_SYSROOT = $(TC_TARGET)/sysroot

include ../../mk/spksrc.tc.mk
