SPK_NAME = socat
SPK_VERS = 1.7.3.4
SPK_REV = 1

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = SynoCommunity
DESCRIPTION = socat - Multipurpose relay \(SOcket CAT)\. Socat is a command line based utility that establishes two bidirectional byte streams and transfers data between them. Because the streams can be constructed from a large set of different types of data sinks and sources, and because lots of address options may be applied to the streams, socat can be used for many different purposes.  

RELOAD_UI = no
DISPLAY_NAME = socat
STARTABLE = no
CHANGELOG = Initial release

HOMEPAGE = http://www.dest-unreach.org/socat/
LICENSE = GPLv2

SPK_COMMANDS = bin/socat bin/filan bin/procan


include ../../mk/spksrc.spk.mk
