PKG_NAME = syno-magnet
PKG_VERS = 1.0
PKG_EXT = tar.gz
PKG_DIST_NAME = v$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = https://github.com/neykov/$(PKG_NAME)/archive
PKG_DIR = $(PKG_NAME)

DEPENDS =

HOMEPAGE = https://github.com/neykov/syno-magnet

CONFIGURE_TARGET = nop
COMPILE_TARGET = nop
INSTALL_TARGET = nop

include ../../mk/spksrc.cross-cc.mk
