PKG_NAME = nasm
PKG_VERS = 2.12.01
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = http://www.nasm.us/pub/nasm/releasebuilds/$(PKG_VERS)
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS =

HOMEPAGE = http://www.nasm.us/
COMMENT  = NASM
LICENSE  = BSD

GNU_CONFIGURE = 1
include ../../mk/spksrc.native-cc.mk
