PKG_NAME = popt
PKG_VERS = 1.16
PKG_EXT = tar.gz
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)
PKG_DIST_NAME = $(PKG_DIR).$(PKG_EXT)
PKG_DIST_SITE = http://rpm5.org/files/$(PKG_NAME)

DEPENDS =

HOMEPAGE = http://rpm5.org/files/popt/
COMMENT  = popt is a command line option parsing library
LICENSE  =

GNU_CONFIGURE = 1
CONFIGURE_ARGS = --disable-static

include ../../mk/spksrc.cross-cc.mk
