TC_ARCH = ppc824x
TC_VERS = 4.2
TC_FIRMWARE = 3.1-1594
TC_KERNEL = 2.6.24
TC_GCC = 3.3.4
TC_GLIBC = 2.3.3

TC_DIST = gcc334_glibc233_ppc824x-GPL
TC_EXT = tgz
TC_DIST_SITE_PATH = PowerPC%20824x%20Linux%202.6.24

TC_TARGET = powerpc-linux
TC_SYSROOT = $(TC_TARGET)
TC_INCLUDE = $(TC_SYSROOT)/include

include ../../mk/spksrc.tc.mk
