SPK_NAME = pixz
SPK_VERS = 1.0.7
SPK_REV = 0
#SPK_ICON = src/pixz.png

#DISPLAY_NAME = pixz
DESCRIPTION = Parallel, indexed xz compressor
HOMEPAGE = https://github.com/vasi/$(SPK_NAME)
LICENSE = 2-Clause BSD
MAINTAINER = dotysan

DEPENDS = cross/$(SPK_NAME)

STARTABLE = no
SPK_COMMANDS = bin/$(SPK_NAME)

include ../../mk/spksrc.spk.mk
