SPK_NAME = pixz
SPK_VERS = 1.0.7
SPK_REV = 1

DEPENDS = cross/pixz

MAINTAINER = dotysan
DESCRIPTION = Parallel, indexed xz compressor.
DISPLAY_NAME = pixz

STARTABLE = no

HOMEPAGE = https://github.com/vasi/pixz
LICENSE = 2-Clause BSD

SPK_COMMANDS = bin/pixz

include ../../mk/spksrc.spk.mk
