SPK_NAME = mergerfs
SPK_VERS = 2.40.2
SPK_REV = 1

DEPENDS = cross/mergerfs

UNSUPPORTED_ARCHS = $(ARMv5_ARCHS) $(PPC_ARCHS)

MAINTAINER = SynoCommunity
DESCRIPTION = mergerfs - a featureful union filesystem.
STARTABLE = no

HOMEPAGE = https://trapexit.github.io/mergerfs/
LICENSE = ISC

SPK_COMMANDS = bin/mergerfs bin/mergerfs-fusermount sbin/mount.mergerfs

include ../../mk/spksrc.spk.mk
