SPK_NAME = ghostscript
SPK_VERS = 10.05.0
SPK_REV = 1
SPK_ICON = src/ghostscript.png

DEPENDS = cross/ghostscript

UNSUPPORTED_ARCHS = comcerto2k

MAINTAINER = hgy59
DESCRIPTION = Ghostscript is an interpreter for the PostScript® language and PDF files.
DISPLAY_NAME = ghostscript
CHANGELOG = "Initial package release."

HOMEPAGE = https://ghostscript.com
LICENSE  = AGPL 3.0

STARTABLE = no

# binaries:
SPK_COMMANDS  = bin/gs
SPK_COMMANDS += bin/gxps
SPK_COMMANDS += bin/gpcl6
# scripts:
SPK_COMMANDS += bin/dvipdf
SPK_COMMANDS += bin/eps2eps
SPK_COMMANDS += bin/gsbj
SPK_COMMANDS += bin/gsdj
SPK_COMMANDS += bin/gsdj500
SPK_COMMANDS += bin/gslj
SPK_COMMANDS += bin/gslp
SPK_COMMANDS += bin/gsnd
SPK_COMMANDS += bin/lprsetup.sh
SPK_COMMANDS += bin/pdf2ps
SPK_COMMANDS += bin/pf2afm
SPK_COMMANDS += bin/pfbtopfa
SPK_COMMANDS += bin/pphs
SPK_COMMANDS += bin/printafm
SPK_COMMANDS += bin/ps2ascii
SPK_COMMANDS += bin/ps2epsi
SPK_COMMANDS += bin/ps2pdf
SPK_COMMANDS += bin/ps2pdf12
SPK_COMMANDS += bin/ps2pdf13
SPK_COMMANDS += bin/ps2pdf14
SPK_COMMANDS += bin/ps2pdfwr
SPK_COMMANDS += bin/ps2ps
SPK_COMMANDS += bin/ps2ps2
SPK_COMMANDS += bin/unix-lpr.sh

include ../../mk/spksrc.spk.mk
