SPK_NAME = bandwhich
SPK_VERS = 0.20.0
SPK_REV = 1

DEPENDS = cross/$(SPK_NAME)

# unknown relocation type 95 ...
UNSUPPORTED_ARCHS = $(OLD_PPC_ARCHS)

MAINTAINER = SynoCommunity
DESCRIPTION = CLI utility for displaying current network utilization by process, connection and remote IP/hostname.
STARTABLE = no

HOMEPAGE = https://github.com/imsnif/bandwhich#readme
LICENSE  = MIT

SPK_COMMANDS = bin/bandwhich

include ../../mk/spksrc.spk.mk
