SPK_NAME = gdu
SPK_VERS = 5.13.2
SPK_REV = 1

DEPENDS = cross/$(SPK_NAME)

UNSUPPORTED_ARCHS = $(PPC_ARCHS)

MAINTAINER = SynoCommunity
DESCRIPTION = Fast disk usage analyzer with console interface written in Go.
DISPLAY_NAME = $(SPK_NAME)
STARTABLE = no

HOMEPAGE = https://github.com/dundee/gdu
LICENSE  = MIT

SPK_COMMANDS = bin/gdu

include ../../mk/spksrc.spk.mk
