SPK_NAME = tmux
SPK_VERS = 2.8
SPK_REV = 4
SPK_ICON = src/tmux.png

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = ymartin59
DESCRIPTION = tmux is a terminal multiplexer, it enables a number of terminals or windows to be accessed and controlled from a single terminal. tmux is intended to be a simple, modern, BSD-licensed alternative to programs such as GNU screen.
RELOAD_UI = no
DISPLAY_NAME = Tmux
STARTABLE = no
CHANGELOG = Update to 2.8

HOMEPAGE   = http://tmux.github.io
LICENSE    = BSD License

SERVICE_SETUP = src/service-setup.sh

include ../../mk/spksrc.spk.mk

