SPK_NAME = tmux
SPK_VERS = 2.9a
SPK_REV = 5
SPK_ICON = src/tmux.png

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = Matthias Lohr
DESCRIPTION = tmux is a terminal multiplexer, it enables a number of terminals or windows to be accessed and controlled from a single terminal. tmux is intended to be a simple, modern, BSD-licensed alternative to programs such as GNU screen.
RELOAD_UI = no
DISPLAY_NAME = Tmux
STARTABLE = no
CHANGELOG = Updated tmux to version 2.9a

HOMEPAGE  = http://tmux.github.io
LICENSE   = BSD License

SPK_LINKS = /usr/local/bin/tmux:bin/tmux-utf8

include ../../mk/spksrc.spk.mk

