PKG_NAME = elfio
PKG_VERS = 3.1
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = http://downloads.sourceforge.net/project/$(PKG_NAME)/ELFIO-sources/ELFIO-$(PKG_VERS)
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS	= 

HOMEPAGE = http://elfio.sourceforge.net/
COMMENT  = ELFIO is a small, header-only C++ library that provides a simple interface for reading and generating files in ELF binary format
LICENSE  = MIT

GNU_CONFIGURE = 1

include ../../mk/spksrc.cross-cc.mk
