TC_ARCH = hi3535
TC_VERS = 6.2.4
TC_KERNEL = 3.4.35
TC_GCC = 4.8.3
TC_GLIBC = 2.19

TC_DIST = hi3535-gcc483_glibc219_hi3535-GPL
TC_DIST_SITE_PATH = HiSilicon%20Hi3535%20Linux%203.4.35

TC_TARGET = arm-cortexa9-linux-gnueabi
TC_SYSROOT = $(TC_TARGET)/sysroot

include ../../mk/spksrc.tc.mk
