SPK_NAME = dos2unix
SPK_VERS = 7.4.3
SPK_REV = 1

DEPENDS = cross/dos2unix

MAINTAINER = SynoCommunity
DESCRIPTION = Convert text files with DOS or Mac line breaks to Unix line breaks and vice versa.
STARTABLE = no

HOMEPAGE = https://waterlan.home.xs4all.nl/dos2unix.html
LICENSE  = FreeBSD style

SPK_COMMANDS = bin/dos2unix bin/unix2dos bin/mac2unix bin/unix2mac 

include ../../mk/spksrc.spk.mk
