SPK_NAME = screen
SPK_VERS = 4.0.3
SPK_REV = 1
SPK_ICON = src/screen.png

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = SynoCommunity
DESCRIPTION = Screen is a full-screen window manager that multiplexes a physical terminal between several processes, typically interactive shells.
DISPLAY_NAME = screen
CHANGELOG = "New version"

HOMEPAGE = https://www.gnu.org/software/screen/
LICENSE  = GPLv2

INSTALLER_SCRIPT = src/installer.sh
SSS_SCRIPT = src/dsm-control.sh
FWPORT =

INSTALL_PREFIX = /usr/local/$(SPK_NAME)

POST_STRIP_TARGET =

include ../../mk/spksrc.spk.mk
