PKG_CONFIG_LIBDIR = $(INSTALL_DIR)/$(INSTALL_PREFIX)/lib/pkgconfig

ifndef INSTALL_DIR
INSTALL_DIR = $(WORK_DIR)/install
endif

ifndef INSTALL_PREFIX
INSTALL_PREFIX = /usr/local
endif

# Unsetting variables MUST always be first
# as otherwise it fails silently
ENV := -u LDSHARED -u MAKEFLAGS -u PKG_CONFIG -u PKG_CONFIG_LIBDIR -u PKG_CONFIG_PATH $(ENV)

ENV += LD= CPP= NM= CC= RANLIB= CXX= AR= STRIP= OBJDUM= CFLAGS="$(NATIVE_CFLAGS)" CPPFLAGS="$(NATIVE_CPPFLAGS)" LDFLAGS="$(NATIVE_LDFLAGS)" CXXFLAGS="$(NATIVE_CXXFLAGS)" READELF= AS= OBJDUMP=
ENV += INSTALL_PREFIX=$(INSTALL_PREFIX)
