###############################################################################
# spksrc.cross-env.mk
#
# Defines the cross-compilation build environment.
#
# Responsibilities:
#   - Define the base ENV variables shared by all build systems
#     (autotools, flags, cmake, meson, rust)
#   - Locate and load tc_vars*.mk files generated by the toolchain
#   - Export toolchain metadata required at all build stages
#   - Configure optional kernel and toolkit environments
#   - Normalize debug / optimization flags across architectures
#
# Execution model:
#   - This file does NOT build the toolchain
#   - tc_vars*.mk files are generated during Stage1 (toolchain bootstrap)
#   - tc_vars*.mk are only loaded if $(TCVARS_DONE) exists
#   - -include is used to avoid hard failures during early evaluation
#
# Design constraints:
#   - Must be included after WORK_DIR is defined
#   - Must tolerate inclusion before tc_vars exist
#   - ENV is the single source of truth passed to sub-makes
#
###############################################################################

ENV += WORK_DIR=$(WORK_DIR)
ENV += INSTALL_PREFIX=$(INSTALL_PREFIX)

PKG_CONFIG_LIBDIR = $(INSTALL_DIR)/$(INSTALL_PREFIX)/lib/pkgconfig
ENV += PKG_CONFIG_LIBDIR=$(PKG_CONFIG_LIBDIR)

# Core toolchain variable definitions
#
# tc_vars.mk is ALWAYS generated for the toolchain and provides the
# canonical identity of the toolchain:
#   - target triple and prefix
#   - sysroot location
#   - compiler / libc / kernel versions
#   - architecture and DSM metadata
#
# This file is framework-agnostic and is ALWAYS loaded once tcvars
# generation is complete, independently of DEFAULT_ENV.
TC_VARS_MK = $(WORK_DIR)/tc_vars.mk
TC_WORK_DIR=$(abspath $(WORK_DIR)/../../../toolchain/$(TC)/work)
ENV += TC_WORK_DIR=$(TC_WORK_DIR)

# Core toolkit variable definitions
#
# tk_vars.mk is ONLY generated if REQUIRE_TOOLKIT=1 for the related
# toolkit and provides the canonical identity of the toolkit:
#   - Toolkit sysroot, binaries, includes and libraries location
#
# This file is framework-agnostic and is ONLY loaded once tkvars.
ifeq ($(strip $(REQUIRE_TOOLKIT)),1)
TK_VARS_MK = $(WORK_DIR)/tk_vars.mk
TK_WORK_DIR=$(abspath $(WORK_DIR)/../../../toolkit/$(TK)/work)
ENV += TK_WORK_DIR=$(TK_WORK_DIR)
endif

ifeq ($(strip $(REQUIRE_KERNEL)),1)
ENV += REQUIRE_KERNEL_MODULE="$(REQUIRE_KERNEL_MODULE)"
KERNEL_ROOT = $(WORK_DIR)/linux
ENV += KERNEL_ROOT=$(KERNEL_ROOT)
endif

# ---------------------------------------------------------------------------
# Toolchain (MANDATORY) + Toolkit (OPTIONAL) environment loading
#
# tc_vars*.mk files are generated during the toolchain bootstrap (Stage1).
# They define compiler, linker, flags and sysroot paths.  Similarly tk_vars.mk
# file is loaded at stage1 only when REQUIRE_TOOLKIT=1.
#
# Two classes of tc_vars files exist:
#   1) tc_vars.mk
#      - Always generated
#      - Defines the canonical toolchain identity
#      - Framework-agnostic
#
#   2) tc_vars.<env>.mk
#      - Generated per build framework
#      - Selected via DEFAULT_ENV
#      - Extend TC_ENV with framework-specific flags
#
#   3) tk_vars.mk
#      - Extend ENV with toolkit specific flags
#
# tc_vars.mk is always loaded once $(TCVARS_DONE) exists.
# tc_vars.<env>.mk files are loaded based on DEFAULT_ENV.
# tk_vars.mk file is loaded based on REQUIRE_TOOLKIT=1.
#
# Result:
#   - TC_ENV is populated
#   - ENV is extended with toolchain-specific variables
# ---------------------------------------------------------------------------
ifneq ($(strip $(TC)),)

# Mandatory to build the CFLAGS and LDFLAGS env variables
export INSTALL_DIR
export INSTALL_PREFIX

# Default is autotools / make
DEFAULT_ENV ?= autotools flags rust

# Map DEFAULT_ENV definitions to filenames
TC_VARS_FILES := $(wildcard $(foreach b,$(DEFAULT_ENV),$(WORK_DIR)/tc_vars.$(b).mk))

# Load full toolchain environment ONLY after tc_vars have been generated
ifeq ($(wildcard $(TCVARS_DONE)),$(TCVARS_DONE))
  ENV += TC=$(TC)
  $(eval -include $(TC_VARS_MK))
  $(eval -include $(TC_VARS_FILES))
  ENV += $(TC_ENV)
endif

# Load full toolkit environment ONLY after tk_vars have been generated
ifeq ($(wildcard $(TKVARS_DONE)),$(TKVARS_DONE))
  ENV += TK=$(TK)
  $(eval -include $(TK_VARS_MK))
endif

endif

# Allow toolchain mandatory variables to
# be available at all build stages in
# particular for dependencies (spksrc.depends.mk)
ENV += TC_GCC=$$(eval $$(echo $(WORK_DIR)/../../../toolchain/syno-$(ARCH)-$(TCVERSION)/work/$(TC_TARGET)/bin/$(TC_PREFIX)gcc -dumpversion) 2>/dev/null || true)
ENV += TC_GLIBC=$(TC_GLIBC)
ENV += TC_KERNEL=$(TC_KERNEL)


# ---------------------------------------------------------------------------
# Debug / optimization flags policy
#
# This section normalizes debug and optimization flags across architectures
# and toolchain capabilities.
#
# Supported modes:
#   - GCC_DEBUG_INFO=1      : full debug builds
#   - GCC_NO_DEBUG_INFO=1   : size-optimized, stripped builds
#
# Architecture-specific adjustments are applied where required.
# ---------------------------------------------------------------------------

# Debug flags (remove any other -O%):
#  -ggdb3 generates extensive debug info optimized for GDB
#  -g3 includes macro definitions in debug info
#  -O0 disables optimizations for predictable debugging
#  -gz compresses debug sections to reduce file size (60-80% smaller)
#
# PowerPC e500v2 (qoriq): Use -O1 to avoid stack frame offset limitations
# (e500v2 has 248-byte max offset for certain load/store instructions)
#
# GCC 4.8.3 (hi3535/armv7l) with old binutils cannot handle compressed
# debug sections from -g3. Use -g (level 2) instead which generates
# less debug info and avoids compression
ifeq ($(strip $(GCC_DEBUG_INFO)),1)
  ifeq ($(strip $(GCC_DEBUG_FLAGS)),)
    ifeq ($(findstring $(ARCH), $(PPC_ARCHS)),$(ARCH))
      GCC_DEBUG_FLAGS = -ggdb3 -g3 -O1 -fno-omit-frame-pointer
    else ifeq ($(findstring $(ARCH), $(ARMv7L_ARCHS)),$(ARCH))
      GCC_DEBUG_FLAGS = -ggdb3 -g3 -O1 -fno-omit-frame-pointer
    else
      GCC_DEBUG_FLAGS = -ggdb3 -g -O0
    endif

    # Check compression support and add to flags
    GCC_SUPPORTS_GZ := $(shell echo | $(WORK_DIR)/../../../toolchain/syno-$(ARCH)-$(TCVERSION)/work/$(TC_TARGET)/bin/$(TC_PREFIX)gcc -gz -E - 2>/dev/null 1>&2 && echo yes)
    ifeq ($(strip $(GCC_SUPPORTS_GZ)),yes)
      GCC_DEBUG_FLAGS += -gz
    endif
  endif

  ADDITIONAL_CFLAGS := $(patsubst -O%,,$(ADDITIONAL_CFLAGS))
  ADDITIONAL_CPPFLAGS := $(patsubst -O%,,$(ADDITIONAL_CPPFLAGS))
  ADDITIONAL_CXXFLAGS := $(patsubst -O%,,$(ADDITIONAL_CXXFLAGS))
  ADDITIONAL_RUSTFLAGS := -Cdebuginfo=2 -Copt-level=0

# gcc:
#  -g0 deactivates debug information generation
#  -Os enable some optimizations while avoiding those that increases space
#  -flto enable optimization at link time (Link Time Optimization)
#  -ffunction-sections -fdata-sections allows placing functions in their own ELF section
# ld:
#  -Wl,--gc-sections allows removing unused functions set previously (-f*-sections)
#  -w omits the DWARF symbol table removing debugging information
#  -s strips the symbol table and debug information from the binary
else ifeq ($(strip $(GCC_NO_DEBUG_INFO)),1)
  GCC_NO_DEBUG_FLAGS = -g0 -Os -ffunction-sections -fdata-sections -fvisibility=hidden
  ADDITIONAL_CFLAGS := $(patsubst -O%,,$(ADDITIONAL_CFLAGS)) $(GCC_NO_DEBUG_FLAGS)
  ADDITIONAL_CPPFLAGS := $(patsubst -O%,,$(ADDITIONAL_CPPFLAGS)) $(GCC_NO_DEBUG_FLAGS)
  ADDITIONAL_CXXFLAGS := $(patsubst -O%,,$(ADDITIONAL_CXXFLAGS)) $(GCC_NO_DEBUG_FLAGS)
  ADDITIONAL_LDFLAGS := $(ADDITIONAL_LDFLAGS) -w -s -Wl,--gc-sections
endif
