PKG_CONFIG_LIBDIR = $(INSTALL_DIR)/$(INSTALL_PREFIX)/lib/pkgconfig

INSTALL_DIR = $(WORK_DIR)/install
INSTALL_PREFIX = /usr/local

# Unsetting variables MUST always be first
# as otherwise it fails silently
ENV := -u LDSHARED -u MAKEFLAGS -u PKG_CONFIG -u PKG_CONFIG_LIBDIR -u PKG_CONFIG_PATH $(ENV)

ENV += AR= AS= CC= CPP= CXX= LD= NM= OBJDUMP= RANLIB= READELF= STRIP=
ENV += CFLAGS="$(NATIVE_CFLAGS)" CPPFLAGS="$(NATIVE_CPPFLAGS)" LDFLAGS="$(NATIVE_LDFLAGS)" CXXFLAGS="$(NATIVE_CXXFLAGS)"
ENV += INSTALL_PREFIX=$(INSTALL_PREFIX)
