PKG_NAME = asyncstdlib
PKG_VERS = 3.9.2
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = https://files.pythonhosted.org/packages/source/a/$(PKG_NAME)
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

HOMEPAGE = https://github.com/maxfischer2781/asyncstdlib
COMMENT  = The missing toolbox for an async world.
LICENSE  = MIT

include ../../mk/spksrc.python-wheel.mk
