TC_ARCH = geminilake
TC_VERS = 7.0
TC_KERNEL = 4.4.180
TC_GLIBC = 2.26

TC_DIST = geminilake-gcc750_glibc226_x86_64-GPL
TC_DIST_SITE_PATH = Intel%20x86%20Linux%204.4.180%20%28GeminiLake%29

TC_TARGET = x86_64-pc-linux-gnu
TC_SYSROOT = $(TC_TARGET)/sys-root

include ../../mk/spksrc.tc.mk
