SPK_NAME = fzf
SPK_VERS = 0.30.0
SPK_REV = 2
SPK_ICON = src/fzf.png

DEPENDS = cross/fzf

MAINTAINER = SynoCommunity
DESCRIPTION = A command-line fuzzy finder.
STARTABLE = no

HOMEPAGE = https://github.com/junegunn/fzf
LICENSE = MIT

SPK_COMMANDS = bin/fzf

include ../../mk/spksrc.spk.mk
