SPK_NAME = fzf
SPK_VERS = 0.25.1
SPK_REV = 1
SPK_ICON = src/fzf.png

DEPENDS = cross/fzf

MAINTAINER = SynoCommunity
DESCRIPTION = A command-line fuzzy finder.
DISPLAY_NAME = fzf
STARTABLE = no
CHANGELOG = Initial release

HOMEPAGE = https://github.com/junegunn/fzf
LICENSE = MIT

SPK_COMMANDS = bin/fzf

include ../../mk/spksrc.spk.mk
