SPK_NAME = fzf
SPK_VERS = 0.67.0
SPK_REV = 1
SPK_ICON = src/fzf.png

UNSUPPORTED_ARCHS = $(PPC_ARCHS)

DEPENDS = cross/fzf

MAINTAINER = SynoCommunity
DESCRIPTION = A command-line fuzzy finder.
STARTABLE = no

HOMEPAGE = https://junegunn.github.io/fzf/
LICENSE = MIT

SPK_COMMANDS = bin/fzf

include ../../mk/spksrc.spk.mk
