PKG_NAME = libconfig
PKG_VERS = 1.7.3
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = https://github.com/hyperrealm/libconfig/releases/download/v$(PKG_VERS)
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS =

HOMEPAGE = https://hyperrealm.github.io/libconfig/
COMMENT  = Simple library for processing structured configuration files.
LICENSE  = LGPL-2.1

GNU_CONFIGURE = 1

include ../../mk/spksrc.cross-cc.mk
