PKG_NAME = libconfig
PKG_VERS = 1.4.9
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = http://www.hyperrealm.com/libconfig
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS =

HOMEPAGE = http://www.hyperrealm.com/libconfig/
COMMENT  = Simple library for processing structured configuration files
LICENSE  =

GNU_CONFIGURE = 1

include ../../mk/spksrc.cross-cc.mk

