SPK_NAME = lsd
SPK_VERS = 1.0.0
SPK_REV = 1

DEPENDS = cross/lsd

MAINTAINER = SynoCommunity
DESCRIPTION = The next gen ls command.
STARTABLE = no

HOMEPAGE = https://github.com/lsd-rs/lsd
LICENSE  = Apache 2.0

SPK_COMMANDS = bin/lsd

include ../../mk/spksrc.spk.mk
