SPK_NAME = rabbitmq-server
SPK_VERS = 3.7.15
SPK_REV = 2
SPK_ICON = src/rabbitmq.png

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = DigitalBox98
DESCRIPTION = RabbitMQ is one of the most popular open source message brokers. From T-Mobile to Runtastic, RabbitMQ is used worldwide at small startups and large enterprises. RabbitMQ is lightweight and easy to deploy on premises and in the cloud. It supports multiple messaging protocols. RabbitMQ can be deployed in distributed and federated configurations to meet high-scale, high-availability requirements.

RELOAD_UI = no
DISPLAY_NAME = RabbitMQ Server
STARTABLE = no

HOMEPAGE   = http://www.rabbitmq.com
LICENSE    = MPL

INSTALLER_SCRIPT = src/installer.sh

include ../../mk/spksrc.spk.mk

