PKG_NAME = libpciaccess
PKG_VERS = 0.14
PKG_EXT = tar.bz2
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = http://xorg.freedesktop.org/archive/individual/lib
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS = 

HOMEPAGE = 
COMMENT  = 
LICENSE = 

GNU_CONFIGURE = 1

include ../../mk/spksrc.cross-cc.mk
