PKG_NAME = libmspack
PKG_VERS = 0.5alpha
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = http://www.cabextract.org.uk/$(PKG_NAME)
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS =

HOMEPAGE = http://www.cabextract.org.uk/libmspack/
COMMENT  = libmspack is a portable library for some loosely related Microsoft compression formats

GNU_CONFIGURE = 1

include ../../mk/spksrc.cross-cc.mk
