PKG_NAME = bcrypt
PKG_VERS = 1.0.2
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = http://pypi.python.org/packages/source/b/$(PKG_NAME)
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS = cross/libffi

HOMEPAGE = http://pypi.python.org/pypi/bcrypt
COMMENT  = Modern password hashing for your software and your servers
LICENSE  =

include ../../mk/spksrc.python-module.mk
