PKG_NAME = bcrypt
PKG_VERS = 2.0.0
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = https://files.pythonhosted.org/packages/source/b/$(PKG_NAME)
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS = cross/cffi

HOMEPAGE = https://github.com/pyca/bcrypt
COMMENT  = Modern password hashing for your software and your servers
LICENSE  = Apache 2.0

include ../../mk/spksrc.python-module.mk
