SPK_NAME = ionice
SPK_VERS = 2.41.1
SPK_REV = 1

DEPENDS = cross/ionice

MAINTAINER = SynoCommunity
DESCRIPTION = ionice of util-linux (random collection of Linux utilities).
STARTABLE = no

HOMEPAGE = https://github.com/util-linux/util-linux
LICENSE  = GPLv2

SPK_COMMANDS = bin/ionice

include ../../mk/spksrc.spk.mk
