# Pelican Panel - Service Setup Script
# Lifecycle hooks for SPK installation/upgrade/uninstall

ENV_EXAMPLE="${SYNOPKG_PKGDEST}/share/panel.env.example"
WINGS_CONFIG_EXAMPLE="${SYNOPKG_PKGDEST}/share/wings.config.example.yml"
VAR_DIR="${SYNOPKG_PKGVAR}"
DATA_DIR="${VAR_DIR}/data"
LOG_DIR="${VAR_DIR}/logs"
ENV_FILE="${VAR_DIR}/panel.env"
WINGS_CONFIG="${DATA_DIR}/wings/config.yml"

# Cleanup function - called on uninstall or failed install
cleanup_package()
{
    # Stop and remove Docker containers
    docker rm -f pelican_panel-panel-1 2>/dev/null || true
    docker rm -f pelican_panel-wings-1 2>/dev/null || true
    docker rm -f pelican_panel-panel 2>/dev/null || true

    # Remove Docker network
    docker network rm pelican_network 2>/dev/null || true

    # Remove user from docker group
    if getent group docker >/dev/null 2>&1 && [ -n "${EFF_USER}" ]; then
        delgroup "${EFF_USER}" docker 2>/dev/null || true
    fi
}

service_preinst()
{
    # Pre-installation checks (none required currently)
    return 0
}

create_data_dirs()
{
    install -d -m 0750 "${VAR_DIR}"
    # Pelican data directory (SQLite DB, uploads, cache)
    mkdir -p "${DATA_DIR}/pelican-data" 2>/dev/null || true
    # Application logs
    mkdir -p "${DATA_DIR}/pelican-logs" 2>/dev/null || true
    # Wings directories
    mkdir -p "${DATA_DIR}/wings" 2>/dev/null || true
    mkdir -p "${DATA_DIR}/servers" 2>/dev/null || true
    mkdir -p "${DATA_DIR}/backups" 2>/dev/null || true
    mkdir -p "${DATA_DIR}/archives" 2>/dev/null || true
    mkdir -p "${DATA_DIR}/wings-logs" 2>/dev/null || true
    # Temp directory for installation scripts (must be accessible by Docker)
    mkdir -p "${DATA_DIR}/tmp" 2>/dev/null || true
    chmod 777 "${DATA_DIR}/tmp" 2>/dev/null || true
    # Package logs
    install -d -m 0750 "${LOG_DIR}" 2>/dev/null || mkdir -p "${LOG_DIR}"
}

generate_app_key()
{
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -base64 32 | tr -d '\n'
    elif command -v python3 >/dev/null 2>&1; then
        python3 -c "import secrets,base64;print(base64.b64encode(secrets.token_bytes(32)).decode())"
    else
        tr -dc 'A-Za-z0-9' </dev/urandom | head -c 43
    fi
}

detect_nas_ip()
{
    # Try to get the primary IP address of the NAS
    # Method 1: Get IP from default route interface
    local default_iface=$(ip route | grep default | head -1 | awk '{print $5}')
    if [ -n "$default_iface" ]; then
        local ip=$(ip -4 addr show "$default_iface" | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | head -1)
        if [ -n "$ip" ]; then
            echo "$ip"
            return
        fi
    fi
    # Method 2: Get first non-localhost IPv4
    ip -4 addr show | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | grep -v '^127\.' | head -1
}

hydrate_env_file()
{
    if [ ! -f "${ENV_FILE}" ] && [ -f "${ENV_EXAMPLE}" ]; then
        install -m 0600 "${ENV_EXAMPLE}" "${ENV_FILE}"

        # Generate APP_KEY
        APP_KEY=$(generate_app_key)
        sed -i "s#APP_KEY=.*#APP_KEY=base64:${APP_KEY}#" "${ENV_FILE}"

        # Apply wizard values - auto-detect IP if not provided or localhost
        local app_host="${wizard_host}"
        if [ -z "$app_host" ] || [ "$app_host" = "localhost" ]; then
            app_host=$(detect_nas_ip)
            # Fallback to localhost if detection fails
            app_host="${app_host:-localhost}"
        fi
        local app_port="8080"  # Fixed port
        local app_url="http://${app_host}:${app_port}"

        sed -i "s#APP_URL=.*#APP_URL=${app_url}#" "${ENV_FILE}"
        sed -i "s#PANEL_PORT=.*#PANEL_PORT=${app_port}#" "${ENV_FILE}"

        # Update Wings Panel URL
        sed -i "s#WINGS_PANEL_URL=.*#WINGS_PANEL_URL=${app_url}#" "${ENV_FILE}"
    fi
}

hydrate_wings_config()
{
    if [ ! -f "${WINGS_CONFIG}" ] && [ -f "${WINGS_CONFIG_EXAMPLE}" ]; then
        install -d -m 0770 "${DATA_DIR}/wings"
        install -m 0640 "${WINGS_CONFIG_EXAMPLE}" "${WINGS_CONFIG}"
    fi
}

# Fix Wings config for Docker-in-Docker on Synology
# This ensures the config works correctly even if generated by the Panel
fix_wings_config()
{
    if [ -f "${WINGS_CONFIG}" ]; then
        # FIX 1: API Port - Panel generates 8445 (external) but container needs 8080 (internal)
        sed -i 's/port: 8445$/port: 8080/' "${WINGS_CONFIG}"

        # FIX 2: System paths - Use host paths instead of container paths
        sed -i "s|/var/lib/pelican/volumes|${DATA_DIR}/servers|g" "${WINGS_CONFIG}"
        sed -i "s|/var/lib/pelican/backups|${DATA_DIR}/backups|g" "${WINGS_CONFIG}"
        sed -i "s|/var/lib/pelican/archives|${DATA_DIR}/archives|g" "${WINGS_CONFIG}"
        sed -i "s|/var/log/pelican|${DATA_DIR}/wings-logs|g" "${WINGS_CONFIG}"

        # Fix root_directory - match with or without trailing content
        sed -i "s|root_directory: /var/lib/pelican$|root_directory: ${DATA_DIR}|" "${WINGS_CONFIG}"

        # FIX 3: Disable mount_passwd - the passwd_file path doesn't exist on host
        sed -i 's/mount_passwd: true/mount_passwd: false/g' "${WINGS_CONFIG}"

        # FIX 4: tmp_directory - Must be a host path for install scripts
        sed -i "s|tmp_directory: /tmp/pelican$|tmp_directory: ${DATA_DIR}/tmp|" "${WINGS_CONFIG}"

        # FIX 5: Fix allowed_origins for WebSocket
        sed -i 's/allowed_origins: \[\]/allowed_origins:\n  - "*"/' "${WINGS_CONFIG}"

        # FIX 6: Prevent Panel from overwriting our config fixes
        sed -i 's/ignore_panel_config_updates: false/ignore_panel_config_updates: true/' "${WINGS_CONFIG}"

        # Create required directories
        mkdir -p "${DATA_DIR}/servers" "${DATA_DIR}/backups" "${DATA_DIR}/archives" "${DATA_DIR}/wings-logs" "${DATA_DIR}/tmp" 2>/dev/null || true
        chmod 777 "${DATA_DIR}/tmp" 2>/dev/null || true
    fi
}


service_postinst()
{
    create_data_dirs
    hydrate_env_file
    hydrate_wings_config
    fix_wings_config  # Apply Docker-in-Docker fixes
    install -d -m 0750 "${VAR_DIR}/runtime"
    touch "${VAR_DIR}/pelican.log"
    chmod 0640 "${VAR_DIR}/pelican.log"

    # Only chown specific files, not recursively (Docker manages its own data permissions)
    if [ -n "${EFF_USER}" ]; then
        chown "${EFF_USER}:${EFF_USER}" "${VAR_DIR}" "${LOG_DIR}" "${VAR_DIR}/runtime" 2>/dev/null || true
        chown "${EFF_USER}:${EFF_USER}" "${ENV_FILE}" "${VAR_DIR}/pelican.log" 2>/dev/null || true
        chown "${EFF_USER}:${EFF_USER}" "${WINGS_CONFIG}" 2>/dev/null || true
    fi

    if getent group docker >/dev/null 2>&1 && [ -n "${EFF_USER}" ]; then
        addgroup "${EFF_USER}" docker 2>/dev/null || true
    fi
}

service_preupgrade()
{
    # Only backup config files - Docker data is persistent and doesn't need copying
    if [ -d "${SYNOPKG_TEMP_UPGRADE_FOLDER}" ]; then
        cp -a "${ENV_FILE}" "${SYNOPKG_TEMP_UPGRADE_FOLDER}/panel.env" 2>/dev/null || true
        cp -a "${WINGS_CONFIG}" "${SYNOPKG_TEMP_UPGRADE_FOLDER}/wings.config.yml" 2>/dev/null || true
    fi
}

service_postupgrade()
{
    # Create any missing directories (for upgrades from older versions)
    create_data_dirs

    # Restore config files only - Docker data stays in place
    if [ -f "${SYNOPKG_TEMP_UPGRADE_FOLDER}/panel.env" ]; then
        install -m 0600 "${SYNOPKG_TEMP_UPGRADE_FOLDER}/panel.env" "${ENV_FILE}"
    fi
    if [ -f "${SYNOPKG_TEMP_UPGRADE_FOLDER}/wings.config.yml" ]; then
        install -m 0640 "${SYNOPKG_TEMP_UPGRADE_FOLDER}/wings.config.yml" "${WINGS_CONFIG}"
    fi

    # Apply Docker-in-Docker fixes to existing config
    fix_wings_config
    # Only chown config files, not the entire data directory
    if [ -n "${EFF_USER}" ]; then
        chown "${EFF_USER}:${EFF_USER}" "${ENV_FILE}" 2>/dev/null || true
        chown "${EFF_USER}:${EFF_USER}" "${WINGS_CONFIG}" 2>/dev/null || true
        chown -R "${EFF_USER}:docker" "${DATA_DIR}" 2>/dev/null || true
    fi
}

service_preuninst()
{
    # Stop containers quickly (1 second timeout instead of default 10)
    docker stop -t 1 pelican_panel-panel-1 2>/dev/null || true
    docker stop -t 1 pelican_panel-wings-1 2>/dev/null || true
    docker stop -t 1 pelican_panel-panel 2>/dev/null || true
}

service_postuninst()
{
    # Always cleanup containers and system files
    cleanup_package

    # Delete data if user chose to
    if [ "${wizard_delete_data}" = "true" ]; then
        rm -rf "/var/packages/pelican_panel/var" 2>/dev/null || true
        rm -rf "/volume1/@appdata/pelican_panel" 2>/dev/null || true
    fi
}
