--- Makefile	2010-11-04 17:14:53.000000000 +0000
+++ Makefile.new	2019-01-18 09:48:35.000000000 +0000
@@ -30,10 +30,12 @@
 TARGETS = $(PROJECT) $(SHAREDLIB) $(STATICLIB)
 
 INSTALL = install
-libdir = /usr/lib
-libexecdir = /usr/lib
-includedir = /usr/include
-mandir = /usr/share/man
+prefix = @INSTALL_PREFIX@
+exec_prefix =${prefix}
+libdir =${exec_prefix}/lib
+libexecdir =${exec_prefix}/lib
+sharedlibdir =${libdir}
+includedir =${prefix}/include
 man3dir = $(mandir)/man3
 DESTDIR =
 
