PKG_NAME = webrtcvad
PKG_VERS = 2.0.10
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_VERS).$(PKG_EXT)
PKG_DIST_FILE = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = https://github.com/wiseman/py-webrtcvad/archive
PKG_DIR = py-$(PKG_NAME)-$(PKG_VERS)

HOMEPAGE = https://github.com/wiseman/py-webrtcvad
COMMENT  = This is a python interface to the WebRTC Voice Activity Detector (VAD). It is compatible with Python 2 and Python 3.
LICENSE  = MIT

include ../../mk/spksrc.python-wheel.mk
