TC_ARCH = x86
TC_VERS = 5.0
TC_KERNEL = 3.2.40
TC_GCC = 4.7.3
TC_GLIBC = 2.17

TC_DIST = gcc473_glibc217_x86_64-GPL
TC_EXT = tgz
TC_DIST_SITE_PATH = Intel%20x86%20Linux%203.2.40%20%28Pineview%29

TC_TARGET = x86_64-pc-linux-gnu
TC_SYSROOT = $(TC_TARGET)/sys-root

include ../../mk/spksrc.tc.mk
