TC_ARCH = armada375
TC_VERS = 7.0
TC_KERNEL = 3.2.101
TC_GLIBC = 2.26

TC_DIST = armada375-gcc750_glibc226_hard-GPL
TC_DIST_SITE_PATH = Marvell%20Armada%20375%20Linux%203.2.101

TC_TARGET = arm-unknown-linux-gnueabi
TC_SYSROOT = $(TC_TARGET)/sysroot
TC_EXTRA_CFLAGS = -mhard-float -mfpu=vfpv3

include ../../mk/spksrc.tc.mk
