PKG_NAME = ghostscript
PKG_VERS = 9.50
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = https://ftp.icm.edu.pl/pub/unix/postscript/ghostscript/gs950
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS =

HOMEPAGE = https://www.ghostscript.com/index.html
COMMENT  = An interpreter for the PostScript language and for PDF.
LICENSE  = GPL Ghostscript, AGPL

GNU_CONFIGURE = 1

include ../../mk/spksrc.native-cc.mk
