SPK_NAME = pigz
SPK_VERS = 2.8
SPK_REV = 1

DEPENDS = cross/pigz

MAINTAINER = SynoCommunity
DESCRIPTION = A parallel implementation of gzip for modern multi-processor, multi-core machines.
DISPLAY_NAME = pigz
STARTABLE = no

HOMEPAGE = https://zlib.net/pigz/
LICENSE = zlib

SPK_COMMANDS = bin/pigz bin/unpigz

include ../../mk/spksrc.spk.mk
