PKG_NAME = Twisted
PKG_VERS = 15.5.0
PKG_EXT = tar.bz2
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = https://files.pythonhosted.org/packages/source/T/$(PKG_NAME)
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS =

HOMEPAGE = http://twistedmatrix.com/
COMMENT  = Twisted is an event-driven networking engine written in Python
LICENSE  = MIT License

include ../../mk/spksrc.python-module.mk
