PKG_NAME = testpkg
# This is a dummy package used to test other package. Add your package to DEPENDS variable.
# e.g. DEPENDS = cross/ffmpeg
DEPENDS = cross/alsa-utils

GNU_CONFIGURE = 1

include ../ncurses/dummy-pkg.mk
include ../../mk/spksrc.cross-cc.mk

