PKG_NAME = termcap
PKG_VERS = 1.3.1
PKG_EXT = tar.gz
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)
PKG_DIST_NAME = $(PKG_DIR).$(PKG_EXT)
PKG_DIST_SITE = http://ftp.gnu.org/gnu/termcap

DEPENDS =

HOMEPAGE = http://www.gnu.org/software/termcap/
COMMENT  =
LICENSE  =

GNU_CONFIGURE = 1

include ../../mk/spksrc.cross-cc.mk
