

PKG_NAME = pip
PKG_VERS = 1.0.2
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = http://pypi.python.org/packages/source/p/$(PKG_NAME)/
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS = cross/setuptools

MAINTAINER = http://packages.nas-forum.com
HOMEPAGE   = http://pypi.python.org/pypi/pip
COMMENT    = pip installs packages. Python packages.
LICENSE    =

ADDITIONAL_CFLAGS =
CONFIGURE_ARGS = 


include ../../mk/spksrc.python-module.mk
