PKG_NAME = tinyxml2
PKG_VERS = 11.0.0
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = https://github.com/leethomason/tinyxml2/archive/refs/tags
PKG_DIST_FILE = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIR = tinyxml2-$(PKG_VERS)

DEPENDS =

HOMEPAGE = https://github.com/leethomason/tinyxml2
COMMENT  = TinyXML2 is a simple, small, efficient, C++ XML parser that can be easily integrated into other programs.
LICENSE  = zlib-license

include ../../mk/spksrc.cross-cmake.mk
