PKG_NAME = docutils
PKG_VERS = 0.12
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = http://sourceforge.net/projects/$(PKG_NAME)/files/$(PKG_NAME)/$(PKG_VERS)
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS = 

HOMEPAGE = http://docutils.sourceforge.net
COMMENT  = Docutils is an open-source text processing system for processing plaintext documentation into useful formats
LICENSE  =

include ../../mk/spksrc.python-module.mk
