TC_NAME = syno-armv7

# generic toolchain for arm7hf DSM
TC_ARCH = armada370 armada375 armada38x alpine alpine4k armadaxp comcerto2k monaco
TC_VERS = 6.2
TC_KERNEL = 3.10.102
TC_GCC = 4.9.3
TC_GLIBC = 2.20

TC_DIST = armada38x-gcc493_glibc220_hard-GPL
TC_DIST_SITE_PATH = Marvell%20Armada%2038x%20Linux%203.10.102

TC_TARGET = arm-unknown-linux-gnueabi
TC_SYSROOT = $(TC_TARGET)/sysroot

include ../../mk/spksrc.tc.mk
