SPK_NAME = he853
SPK_VERS = 1.0.3
SPK_REV  = 2
SPK_ICON = src/HE853.png

DEPENDS = cross/$(SPK_NAME)
REQUIRED_DSM = 5.0

MAINTAINER = ymartin59
DESCRIPTION = HomeEasy HE853 USB device executable - https://github.com/hphde/he853-cli - Allows usage of 433MHz HomeEasy and Smartwares devices from your NAS.
RELOAD_UI = no
DISPLAY_NAME = HomeEasy HE853 USB device executable
STARTABLE = no
CHANGELOG = "Build for DSM 6.1 and upper"
BETA = 1

MAINTAINER = hphde
HOMEPAGE   = https://github.com/hphde/he853-cli
LICENSE    = GPLv2

SERVICE_SETUP = src/service-setup.sh

include ../../mk/spksrc.spk.mk
