PKG_NAME = Cheetah
PKG_VERS = 2.4.4
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = https://files.pythonhosted.org/packages/source/C/$(PKG_NAME)
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS =

HOMEPAGE = http://www.cheetahtemplate.org/
COMMENT  = Cheetah is a template engine and code generation tool.
LICENSE  = MIT License

include ../../mk/spksrc.python-module.mk

