KERNEL_ARCH = v1000nk
KERNEL_VERS = 7.2
KERNEL_BUILD = 72806
KERNEL_DIST = linux-5.10.x
KERNEL_BASE_ARCH = x86
KERNEL_URL_VERSION = 7.2
# v1000nk sources are not published but
# configuration do reside in epyc7002 sources
KERNEL_URL_DIR = epyc7002
KERNEL_CONFIG = synology/synoconfigs/v1000lk5

include ../../mk/spksrc.kernel.mk
