SPK_NAME = detox
SPK_VERS = 1.4.5
SPK_REV = 1
SPK_ICON = src/detox_logo.png

DEPENDS = cross/detox

MAINTAINER = SynoCommunity
DESCRIPTION = detox is a program that renames files to make them easier to work with under Unix and related operating systems. Spaces and various other unsafe characters \(such as '$$'\) get replaced with '_'. ISO 8859-1 \(Latin-1\) characters can be transliterated to ASCII, as can UTF-8 characters.
STARTABLE = no

HOMEPAGE = http://detox.sourceforge.net/
LICENSE = 3-clause BSD

SPK_COMMANDS = bin/detox bin/inline-detox

include ../../mk/spksrc.spk.mk
