SPK_NAME = rnm
SPK_VERS = 4.0.6
SPK_REV = 1

DEPENDS = cross/rnm

MAINTAINER = SynoCommunity
DESCRIPTION = rnm renames files/directories in bulk. Naming scheme (Name String) can be applied or regex replace can be performed to modify file names on the fly. It uses PCRE2 (revised version of PCRE) regex to provide search (and replace) functionality.
RELOAD_UI = no
DISPLAY_NAME = rnm
STARTABLE = no
CHANGELOG = Initial release

HOMEPAGE = https://neurobin.org/projects/softwares/unix/rnm/
LICENSE = GPL v3.0

SERVICE_SETUP = src/service-setup.sh

include ../../mk/spksrc.spk.mk
