SPK_NAME = mtr
SPK_VERS = 0.94
SPK_REV = 1

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = SynoCommunity
DESCRIPTION = mtr \(My traceroute\) combines the functionality of the 'traceroute' and 'ping' programs in a single network diagnostic tool.
DISPLAY_NAME = My traceroute
STARTABLE = no

HOMEPAGE = https://www.bitwizard.nl/mtr/
LICENSE  = GPLv2

SPK_COMMANDS = sbin/mtr sbin/mtr-packet

include ../../mk/spksrc.spk.mk
