SPK_NAME = procs
SPK_VERS = 0.12.3
SPK_REV = 1

DEPENDS = cross/$(SPK_NAME)

UNSUPPORTED_ARCHS = $(OLD_PPC_ARCHS)

MAINTAINER = SynoCommunity
DESCRIPTION = A modern replacement for ps written in Rust.
STARTABLE = no

HOMEPAGE = https://github.com/dalance/procs#readme
LICENSE  = MIT

SPK_COMMANDS = bin/procs

include ../../mk/spksrc.spk.mk
