SPK_NAME = dialog
SPK_VERS = 1.3-20260107
SPK_REV = 1

DEPENDS = cross/dialog

MAINTAINER = SynoCommunity
DESCRIPTION = dialog is a script-interpreter which provides a set of curses widgets. Widgets are objects whose appearance and behavior can be customized.
STARTABLE = no

HOMEPAGE = https://invisible-island.net/dialog/
LICENSE = LGPL 2.1

SPK_COMMANDS = bin/dialog

include ../../mk/spksrc.spk.mk
