SPK_NAME = fritzctl
SPK_VERS = 1.4.23
SPK_REV = 1
SPK_ICON = src/$(SPK_NAME).png

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = bpicode
DESCRIPTION = A lightweight, easy to use console client for the AVM FRITZ!Box Home Automation.
DISPLAY_NAME = fritzctl
STARTABLE = no
CHANGELOG = Initial release

HOMEPAGE = https://github.com/bpicode/fritzctl
LICENSE = MIT

SPK_COMMANDS = bin/fritzctl

GENERIC_ARCHS = ARM7
UNSUPPORTED_ARCHS = $(PPC_ARCHES)

include ../../mk/spksrc.spk.mk
