PKG_NAME = xxHash
PKG_VERS = 0.8.1
PKG_EXT = tar.gz
PKG_DIST_NAME = v$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = https://github.com/Cyan4973/xxHash/archive
PKG_DIST_FILE = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS =

HOMEPAGE = www.xxhash.com
COMMENT  = Extremely fast non-cryptographic hash algorithm.
LICENSE  = 2-Clause BSD

CONFIGURE_TARGET = nop

include ../../mk/spksrc.cross-cc.mk
