PKG_NAME = xxHash
PKG_VERS = 0.8.0
PKG_EXT = tar.gz
PKG_DIST_NAME = v$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = https://github.com/Cyan4973/xxHash/archive
PKG_DIST_FILE = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)


# https://github.com/Cyan4973/xxHash/archive/refs/tags/v0.8.0.tar.gz

DEPENDS =

HOMEPAGE = 
COMMENT  = 
LICENSE  = 

CONFIGURE_TARGET = nop

include ../../mk/spksrc.cross-cc.mk
