PKG_NAME = pydantic-core
PKG_VERS = 2.27.2
PKG_EXT = tar.gz
PKG_DIST_NAME = v$(PKG_VERS).$(PKG_EXT)
PKG_DIST_FILE = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = https://github.com/pydantic/pydantic-core/archive/refs/tags
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS = 

HOMEPAGE = https://github.com/pydantic/pydantic-core
COMMENT  = Provides the core functionality for pydantic validation and serialization.
LICENSE  = MIT license

include ../../mk/spksrc.python-wheel.mk
