SPK_NAME = patch
SPK_VERS = 2.7.6
SPK_REV = 1

DEPENDS = cross/patch

MAINTAINER = SynoCommunity
DESCRIPTION = Patch takes a patch file containing a difference listing produced by the diff program and applies those differences to one or more original files, producing patched versions.
STARTABLE = no

HOMEPAGE = https://savannah.gnu.org/projects/patch/
LICENSE  = GPLv3+

SPK_COMMANDS = bin/patch

include ../../mk/spksrc.spk.mk
