SPK_NAME = fdupes
SPK_VERS = 2.3.2
SPK_REV = 1
SPK_ICON = src/fdupes.png

DEPENDS = cross/fdupes

MAINTAINER = biyiklioglu
DESCRIPTION = FDUPES is a program for identifying or deleting duplicate files residing within specified directories.
DISPLAY_NAME = FDUPES
STARTABLE = no

HOMEPAGE = https://github.com/adrianlopezroche/fdupes/
LICENSE = MIT
HELP_URL = https://github.com/adrianlopezroche/fdupes/wiki

SPK_COMMANDS = bin/fdupes

include ../../mk/spksrc.spk.mk
