
SPK_NAME = hastation
SPK_VERS = 1.0
SPK_REV = 1
SPK_ICON = src/python.png

DEPENDS  = cross/python27 cross/pyalsa cross/pyaudio
DEPENDS += cross/espeak cross/flite cross/speechd
DEPENDS += cross/julius

MAINTAINER = http://packages.nas-forum.com/
COMMENT    = "Home Automation Station"
ADMIN_PORT = 
RELOAD_UI = yes
DISPLAY_NAME = H.A. Station

HOMEPAGE   = 
LICENSE    =

INSTALLER_SCRIPT = src/installer.sh
SSS_SCRIPT       = 
ADDITIONAL_SCRIPTS = 

INSTALL_PREFIX = /usr/local/$(SPK_NAME)


include ../../mk/spksrc.spk.mk
