SPK_NAME = git
SPK_VERS = 2.37.2
SPK_REV = 24
SPK_ICON = src/git.png

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = SynoCommunity
DESCRIPTION = Git is a fast, scalable, distributed revision control system with an unusually rich command set that provides both high-level operations and full access to internals.
DESCRIPTION_FRE = Git est un système de gestion de révision rapide, extensible et distribué avec un ensemble de commandes inhabituellement riche qui fournit à la fois des opérations de haut niveau et un accès complet aux structures de bas niveau.
STARTABLE = no
DISPLAY_NAME = Git
CHANGELOG = "1. Update git to v2.37.2 - Fix for CVE-2022-29187 and various fixes.<br/>2. Update openssl to v1.1.1q."

HOMEPAGE = https://git-scm.com
LICENSE  = GPLv2

SPK_COMMANDS = bin/git bin/git-cvsserver bin/git-receive-pack bin/git-shell bin/git-upload-archive bin/git-upload-pack

include ../../mk/spksrc.spk.mk
