KERNEL_ARCH = northstarplus
KERNEL_VERS = 1.2
KERNEL_BUILD = 7742
KERNEL_EXT = tbz
KERNEL_DIST = linux-3.6.x
KERNEL_CONFIG = synoconfigs/broadcom_northstarplus
KERNEL_BASE_ARCH = arm

include ../../mk/spksrc.kernel.mk
