TC_NAME = syno-$(TC_ARCH)

TC_ARCH = 88f6281
TC_VERS = 5.1
TC_FIRMWARE = 5.0-4458

TC_DIST_NAME = gcc464_glibc215_88f6281-GPL.tgz

TC_EXT = tgz
TC_DIST_SITE = http://sourceforge.net/projects/dsgpl/files/DSM%205.1%20Tool%20Chains/Marvell%2088F628x%20Linux%202.6.32

TC_BASE_DIR = arm-marvell-linux-gnueabi
TC_PREFIX = arm-marvell-linux-gnueabi
TC_TARGET = arm-marvell-linux-gnueabi

TC_CFLAGS =
TC_CPPFLAGS =
TC_CXXFLAGS =
TC_LDFLAGS =

include ../../mk/spksrc.tc.mk
