TC_ARCH = 88f6281
TC_VERS = 5.1
TC_FIRMWARE = 5.0-4458

TC_DIST = gcc464_glibc215_88f6281-GPL
TC_EXT = tgz
TC_DIST_SITE = https://sourceforge.net/projects/dsgpl/files/Tool%20Chain/DSM%205.1%20Tool%20Chains/Marvell%2088F628x%20Linux%202.6.32

TC_PREFIX = arm-marvell-linux-gnueabi
TC_SYSROOT = $(TC_PREFIX)/libc
TC_LIBRARY = $(TC_SYSROOT)/usr/lib

include ../../mk/spksrc.tc.mk
