SVC_BACKGROUND=y
SVC_WRITE_PID=y
NODE_EXPORTER="${SYNOPKG_PKGDEST}/bin/node_exporter"
PARAMETERS_FILE="${SYNOPKG_PKGVAR}/parameters.txt"
PARAMETERS=$(cat ${PARAMETERS_FILE} 2>/dev/null | grep -v "^#" | xargs)
SERVICE_COMMAND="${NODE_EXPORTER} ${PARAMETERS}"
