PKG_NAME = unixODBC
PKG_VERS = 2.3.2
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = ftp://ftp.unixodbc.org/pub/$(PKG_NAME)
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)


DEPENDS =  

HOMEPAGE = http://www.unixodbc.org/
COMMENT  = 
LICENSE  =


GNU_CONFIGURE = 1
CONFIGURE_ARGS = 

include ../../mk/spksrc.cross-cc.mk