name: Bug report
description: Create a report to help us improve
labels: bug
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report!
- type: input
  attributes:
    label: Package
    description: Which package is the bug report abour?
  validations:
    required: true
- type: input
  attributes:
    label: Package Version
    description: What package version do you have installed?
  validations:
    required: true
- type: input
  attributes:
    label: Model
    description: Which NAS Model have you experienced the bug with?
  validations:
    required: true
- type: input
  attributes:
    label: Architecture
    description: Which CPU Architecture does your NAS have? [You can look up the Architectrue for your NAS here](https://github.com/SynoCommunity/spksrc/wiki/Synology-and-SynoCommunity-Package-Architectures)
  validations:
    required: true
- type: input
  attributes:
    label: Firmware Version
    description: Which DSM/SRM version is the NAS running?
  validations:
    required: true
    
- type: textarea
  attributes:
    label: Expected Behaviour / Description
    description: Please tell us you expteded to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Actual Behaviour
    description: Please tell us what happens instead.
  validations:
    required: false
- type: textarea
  attributes:
    label: Reproduction steps
    description: "How do you trigger this bug? Please walk us through it step by step."
    value: |
      1.
      2.
      3.
      ...
    render: bash
  validations:
    required: true
- type: textarea
  attributes:
    label: Install Log
    description: "Please copy the log file from `/var/log/packages/{package}.log` or for DSM<6: `/var/packages/{package}/target/var/{package}_installer.log` in here"
    render: log
  validations:
    required: true
- type: textarea
  attributes:
    label: Service Log
    description: "Please copy the log file from `/var/packages/{package}/var/{package}.log` or for DSM<6: `/var/packages/{package}/target/var/{package}.log` in here if the package is a service."
    render: log
  validations:
    required: false
- type: textarea
  attributes:
    label: Other Logs
    description: "Please copy any other log files from `/var/log/messages`, `/var/log/synopkg.log` or application specific log files in here"
    render: log
  validations:
    required: false
