blank_issues_enabled: false
contact_links:
  - name: Questions and support
    url: https://discord.gg/nnN9fgE7EF
    about: Answers to questions, other kinds of help and support is also available at Discord
