blank_issues_enabled: false
contact_links:
  - name: Questions and support
    url: https://discord.gg/nnN9fgE7EF
    about: Answers to questions and other kinds of help support is also provided at Discord
