KERNEL_ARCH = aarch64
KERNEL_VERS = 6.1
KERNEL_BUILD = 15152
KERNEL_DIST = linux-4.4.x
KERNEL_BASE_ARCH = arm64
KERNEL_URL_DIR = rtd1296-source
KERNEL_CONFIG = synoconfigs/rtd1296

include ../../mk/spksrc.kernel.mk
