IMMICH_BUILD_DATA=@immich_build_data@
IMMICH_MEDIA_LOCATION=@media_path@
IMMICH_MACHINE_LEARNING_URL=@ml_url@
IMMICH_MACHINE_LEARNING_ENABLED=@ml_enabled@
DB_PASSWORD=@db_password@
DB_HOSTNAME=@db_hostname@
DB_PORT=@db_port@
DB_USERNAME=@db_username@
REDIS_HOSTNAME=@redis_hostname@
