PKG_NAME = pymysql_sa
PKG_VERS = 1.0
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = http://pypi.python.org/packages/source/p/$(PKG_NAME)
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS =

HOMEPAGE = https://evax.fr
COMMENT  = This package provides a PyMySQL dialect for SQLAlchemy
LICENSE  = MIT

include ../../mk/spksrc.python-module.mk
