SPK_NAME = ncdu
SPK_VERS = 1.21
SPK_REV = 1

DEPENDS = cross/ncdu

MAINTAINER = yeled
DESCRIPTION = Disk usage analyzer with an ncurses interface.
STARTABLE = no

HOMEPAGE = https://dev.yorhel.nl/ncdu
LICENSE = MIT

SPK_COMMANDS = bin/ncdu

include ../../mk/spksrc.spk.mk
