SPK_NAME = ncdu
SPK_VERS = 1.14.1
SPK_REV = 2
SPK_ICON = src/ncdu.png

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = yeled
DESCRIPTION = Disk usage analyzer with an ncurses interface
RELOAD_UI = no
DISPLAY_NAME = ncdu
STARTABLE = no
CHANGELOG = "Initial release"

HOMEPAGE   = https://dev.yorhel.nl/ncdu
LICENSE    = MIT

SERVICE_SETUP = src/service-setup.sh

include ../../mk/spksrc.spk.mk
