PKG_NAME = regex
PKG_VERS = 2016.03.02
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = https://files.pythonhosted.org/packages/source/r/$(PKG_NAME)
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS =

HOMEPAGE = https://bitbucket.org/mrabarnett/mrab-regex
COMMENT  = Alternative regular expression module, to replace re
LICENSE  = Python Software Foundation License

include ../../mk/spksrc.python-wheel.mk
