SPK_NAME = rclone
SPK_VERS = 1.69.1
SPK_REV = 1
SPK_ICON = src/logo.png

DEPENDS = cross/rclone

UNSUPPORTED_ARCHS = $(PPC_ARCHS)

MAINTAINER = dotwee
DESCRIPTION = Rclone is a command-line program to manage files on cloud storage. It is a feature-rich alternative to cloud vendors' web storage interfaces.
DISPLAY_NAME = rclone
STARTABLE = no

CHANGELOG = "Initial release."

HOMEPAGE = https://rclone.org/
HELPURL = https://rclone.org/docs/

LICENSE  = MIT

SPK_COMMANDS = bin/rclone

include ../../mk/spksrc.spk.mk
