SPK_NAME = rclone
SPK_VERS = 1.72.1
SPK_REV = 3
SPK_ICON = src/rclone.png

DEPENDS = cross/rclone

UNSUPPORTED_ARCHS = $(PPC_ARCHS) $(ARMv5_ARCHS)

MAINTAINER = dotwee
DESCRIPTION = Rclone is a command-line program to manage files on cloud storage. It is a feature-rich alternative to cloud vendors' web storage interfaces.
DISPLAY_NAME = rclone
STARTABLE = no

CHANGELOG = "Update to v1.72.1."

HOMEPAGE = https://rclone.org/
HELPURL = https://rclone.org/docs/

LICENSE  = MIT

SPK_COMMANDS = bin/rclone

include ../../mk/spksrc.spk.mk
