PKG_NAME = rencode
PKG_VERS = 1.0.6
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = https://files.pythonhosted.org/packages/source/r/$(PKG_NAME)
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS =

HOMEPAGE = https://github.com/aresch/rencode
COMMENT  = Python module for fast (basic) object serialization similar to bencode.
LICENSE  = GPLv3

include ../../mk/spksrc.python-module.mk
