SPK_NAME = synocli-kernel
SPK_VERS = 1
SPK_REV = 1
SPK_ICON = src/SynoPackagegreen-kernel.png
DSM_UI_DIR = app
CHANGELOG = "Initial package release"

DEPENDS = cross/usbutils

MAINTAINER = th0ma7
DESCRIPTION = "SynoCli Kernel Tools provides a set of small command-line utilities: usb-devices, usbhid-dump"

STARTABLE = no
DISPLAY_NAME = Kernel-Utils

HOMEPAGE = https://synocommunity.com/
LICENSE  = Each tool is licensed under it\'s respective license.

SPK_COMMANDS  = bin/usb-devices
SPK_COMMANDS += bin/usbhid-dump

include ../../mk/spksrc.spk.mk
