SPK_NAME = links
SPK_VERS = 2.12
SPK_REV = 1
SPK_ICON = src/links.png

DEPENDS = cross/links

MAINTAINER = SynoCommunity
DESCRIPTION = Links is a web browser running in text mode.
DISPLAY_NAME = Links
STARTABLE = no
BETA = 1

HOMEPAGE = http://links.twibright.com/
LICENSE = GPLv2

INSTALLER_SCRIPT = src/installer.sh
SSS_SCRIPT       = src/dsm-control.sh

INSTALL_PREFIX = /usr/local/$(SPK_NAME)

include ../../mk/spksrc.spk.mk
