PKG_NAME = libnuma
PKG_VERS = 2.0.11
PKG_EXT = tar.gz
PKG_DIST_NAME = numactl-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = https://src.fedoraproject.org/repo/pkgs/numactl/numactl-2.0.11.tar.gz/md5/d3bc88b7ddb9f06d60898f4816ae9127
PKG_DIR = numactl-$(PKG_VERS)

DEPENDS =

HOMEPAGE = http://oss.sgi.com/projects/libnuma/
COMMENT  = NUMA stands for Non-Uniform Memory Access.
LICENSE  = GPLv2

GNU_CONFIGURE = 1

include ../../mk/spksrc.cross-cc.mk

