
CONFIG_FILE="${SYNOPKG_PKGVAR}/config.toml"
SERVICE_COMMAND="${SYNOPKG_PKGDEST}/bin/qui serve --config-dir=${CONFIG_FILE}"
SVC_WRITE_PID=y
SVC_BACKGROUND=y

service_postinst ()
{
    # The session secret is required to encrypt passwords.
    # It is only autogenerated when the config.toml is created by qui - either on
    # first start or running with parameter "generate-config".
    # Since we installed a custom config.toml with DSM specific settings, we need
    # to set the sessionSecret at first start.
    if grep -q "_session_secret_" "${CONFIG_FILE}"; then
        # generate secret:
        SESSION_SECRET=$(head -c 32 /dev/urandom | xxd -p | tr -d '[:space:]')
        
        # write SESSION_SECRET to the config file:
        sed "s/_session_secret_/${SESSION_SECRET}/" -i ${CONFIG_FILE}
    fi
}
