TC_NAME = syno-x64

TC_ARCH = apollolake avoton braswell broadwell broadwellnk broadwellnkv2 broadwellntbap bromolow cedarview denverton epyc7002 dockerx64 geminilake grantley purley kvmx64 r1000 v1000 x86 x86_64
TC_VERS = 7.0
TC_KERNEL = 4.4.180
TC_GLIBC = 2.26

TC_DIST = apollolake-gcc750_glibc226_x86_64-GPL
TC_DIST_SITE_PATH = Intel%20x86%20Linux%204.4.180%20%28Apollolake%29

TC_TARGET = x86_64-pc-linux-gnu
TC_SYSROOT = $(TC_TARGET)/sys-root

include ../../mk/spksrc.tc.mk
