TC_NAME = syno-x64

TC_ARCH = apollolake avoton braswell broadwell broadwellnk broadwellnkv2 broadwellntbap bromolow denverton epyc7002 geminilake geminilakenk grantley kvmx64 purley r1000 r1000nk v1000 v1000nk
TC_VERS = 7.2
# kernel is "4.4.302+"; despite TC_DIST_SITE_PATH is "Intel x86 Linux 4.4.180 (Apollolake)"
TC_KERNEL = 4.4.302
TC_GLIBC = 2.36

TC_DIST = apollolake-gcc1220_glibc236_x86_64-GPL
TC_DIST_SITE_PATH = Intel%20x86%20Linux%204.4.180%20%28Apollolake%29

TC_TARGET = x86_64-pc-linux-gnu
TC_SYSROOT = $(TC_TARGET)/sys-root

include ../../mk/spksrc.tc.mk
