TC_NAME = syno-x64

TC_ARCH = apollolake avoton braswell broadwell broadwellnk broadwellnkv2 broadwellntbap bromolow denverton epyc7002 geminilake grantley kvmx64 purley r1000 v1000
TC_VERS = 7.2
TC_KERNEL = 4.4.302
TC_GLIBC = 2.36

TC_DIST = apollolake-gcc1220_glibc236_x86_64-GPL
TC_DIST_SITE_PATH = Intel%20x86%20Linux%204.4.302%20%28Apollolake%29

TC_TARGET = x86_64-pc-linux-gnu
TC_SYSROOT = $(TC_TARGET)/sys-root

include ../../mk/spksrc.tc.mk
