TC_NAME = syno-ppc854x

TC_DIST_NAME = gcc343_glibc234_ppc854x-GPL.tgz

TC_EXT = tgz
TC_DIST_SITE = http://sourceforge.net/projects/dsgpl/files/DSM%204.0%20Tool%20Chains/PowerPC%20854x%20Linux%202.6.32

TC_BASE_DIR = powerpc-linux-gnuspe
TC_PREFIX = powerpc-linux-gnuspe
TC_TARGET = powerpc-unknown-linux

TC_CFLAGS = -mcpu=8548 -mhard-float -mfloat-gprs=double
TC_LDFLAGS =

include ../../mk/spksrc.tc.mk

