SPK_NAME = duf
SPK_VERS = 0.7.0
SPK_REV = 1

DEPENDS = cross/$(SPK_NAME)

UNSUPPORTED_ARCHS = $(PPC_ARCHS)

MAINTAINER = SynoCommunity
DESCRIPTION = Disk Usage/Free Utility - a better 'df' alternative.
DISPLAY_NAME = duf
STARTABLE = no

HOMEPAGE = https://github.com/muesli/duf
LICENSE  = MIT

SPK_COMMANDS = bin/duf

include ../../mk/spksrc.spk.mk
