SPK_NAME = iperf2
SPK_VERS = 2.1.4
SPK_REV = 3
SPK_ICON = src/iperf2.png

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = hgy59
DESCRIPTION = A tool for measuring TCP and UDP network performance, based on iperf 2.0.5.
DISPLAY_NAME = iperf2
STARTABLE = no

HOMEPAGE = https://sourceforge.net/projects/iperf2/
LICENSE = BSD

SPK_COMMANDS = bin/iperf2

include ../../mk/spksrc.spk.mk
