/**
 * Icinga 2 Agent Configuration
 * Constants for agent connecting to master
 */

const PluginDir = "@@PLUGIN_DIR@@"
const ManubulonPluginDir = "@@PLUGIN_DIR@@"
const NodeName = "@@NODE_NAME@@"
const ZoneName = "default"
const ApiBindHost = "0.0.0.0"
const ApiBindPort = "5665"
