/**
 * Icinga 2 Agent Configuration
 */

include "constants.conf"
include "zones.conf"

object IcingaApplication "app" {
}

object ApiListener "api" {
  accept_commands = true
  accept_config = true
}
