/**
 * Icinga 2 Agent Configuration
 */

include "constants.conf"
include "zones.conf"
include <itl>
include <plugins>
include <plugins-contrib>
include <manubulon>
include <nscp>
include "features-enabled/*.conf"

object IcingaApplication "app" {
}

object ApiListener "api" {
  accept_commands = true
  accept_config = true
}
