/**
 * Zones configuration for agent
 * Connects to master server
 */

object Endpoint "@@MASTER_ZONE@@" {
  host = "@@MASTER_HOST@@"
  port = "@@MASTER_PORT@@"
}

object Zone "@@MASTER_ZONE@@" {
  endpoints = [ "@@MASTER_ZONE@@" ]
}

object Endpoint "@@AGENT_NAME@@" {
}

object Zone "@@AGENT_NAME@@" {
  parent = "@@MASTER_ZONE@@"
  endpoints = [ "@@AGENT_NAME@@" ]
}
