/**
 * Zones configuration for agent
 * Connects to master server
 */

object Endpoint "master" {
  host = "@@MASTER_HOST@@"
  port = "@@MASTER_PORT@@"
}

object Zone "master" {
  endpoints = [ "master" ]
}

object Endpoint "@@AGENT_NAME@@" {
}

object Zone "@@AGENT_NAME@@" {
  parent = "master"
  endpoints = [ "@@AGENT_NAME@@" ]
}
