/**
 * Zones configuration for agent
 * Connects to master server
 */

object Endpoint "@@MASTER_ZONE@@" {
  host = "@@MASTER_HOST@@"
  port = "@@MASTER_PORT@@"
}

object Zone "@@MASTER_ZONE@@" {
  endpoints = [ "@@MASTER_ZONE@@" ]
}

object Endpoint "@@AGENT_NAME@@" {
}

object Zone "@@AGENT_NAME@@" {
  parent = "@@MASTER_ZONE@@"
  endpoints = [ "@@AGENT_NAME@@" ]
}

/*
 * Global zones for distributed setups with masters,
 * satellites and clients.
 * Required to sync configuration commands, templates,
 * apply rules, etc. to satellite and clients.
 * All nodes require the same configuration and must
 * have `accept_config` enabled in the `api` feature.
 */

object Zone "global-templates" {
  global = true
}

object Zone "director-global" {
  global = true
}
