SPK_NAME = erlang
SPK_VERS = 26.2.5.16
SPK_REV = 6
SPK_ICON = src/erlang.png

DEPENDS = cross/erlang

MAINTAINER = DigitalBox98
DESCRIPTION = Erlang is a programming language used to build massively scalable soft real-time systems with requirements on high availability. Some of its uses are in telecoms, banking, e-commerce, computer telephony and instant messaging. Erlang's runtime system has built-in support for concurrency, distribution and fault tolerance.
CHANGELOG = "1. Update Erlang to v26.2.5.16"
STARTABLE = no
DISPLAY_NAME = Erlang

HOMEPAGE = https://www.erlang.org
LICENSE  = Apache 2.0

SPK_COMMANDS = bin/erl bin/erlc bin/escript

include ../../mk/spksrc.spk.mk
