PKG_NAME = pyOpenSSL
PKG_VERS = 0.13.1
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = http://pypi.python.org/packages/source/p/$(PKG_NAME)
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS = cross/openssl

HOMEPAGE = https://launchpad.net/pyopenssl
COMMENT  = Python interface to the OpenSSL library
LICENSE  = Apache License

include ../../mk/spksrc.python-module.mk

