SPK_NAME = ffmpeg
SPK_VERS = 3.4.2
SPK_REV = 10
SPK_ICON = src/ffmpeg.png
CHANGELOG = "1. Update ffmpeg to 3.4.2 <br>2. Add VAAPI for intel x64 processors"

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = cytec
DESCRIPTION = FFmpeg is a complete, cross-platform solution to record, convert and stream audio and video. It includes libavcodec - the leading audio/video codec library.
DISPLAY_NAME = ffmpeg
STARTABLE = no

HOMEPAGE = http://www.ffmpeg.org/
LICENSE  = LGPL 2.1

include ../../mk/spksrc.spk.mk
