PKG_NAME = wheel
PKG_VERS = 0.32.3
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = https://files.pythonhosted.org/packages/source/w/$(PKG_NAME)
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS = cross/setuptools

HOMEPAGE = https://bitbucket.org/pypa/wheel
COMMENT  = A built-package format for Python
LICENSE  = MIT

include ../../mk/spksrc.python-module.mk
