PKG_NAME = iksemel
PKG_VERS = 1.4
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = http://iksemel.googlecode.com/files
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS = 

HOMEPAGE = http://code.google.com/p/iksemel/
COMMENT  = Iksemel is an XML (eXtensible Markup Language) parser library designed for Jabber applications
LICENSE  = LGPL

GNU_CONFIGURE = 1

include ../../mk/spksrc.cross-cc.mk

