SPK_NAME = tcl
SPK_VERS = 8.6.9
SPK_REV = 3
SPK_ICON = src/tcl.png

DEPENDS = cross/$(SPK_NAME)

MAINTAINER	= Tcl developer Xchange
MAINTAINER_URL	= https://www.tcl.tk/
DISTRIBUTOR	= SynoCommunity
DISTRIBUTOR_URL	= https://synocommunity.com/
HELPURL		= https://www.tcl.tk/doc/

DESCRIPTION = Tcl \(Tool Command Language\) is a very powerful but easy to learn dynamic programming language, suitable for a very wide range of uses, including web and desktop applications, networking, administration, testing and many more. Open source and business-friendly, Tcl is a mature yet evolving language that is truly cross platform, easily deployed and highly extensible.
RELOAD_UI = no
DISPLAY_NAME = Tcl
STARTABLE = no
CHANGELOG = "1. Update to 8.6.9<br/>2. Use framework generic installer<br/>3. Fixed Tcl shell variables and packages, fixed 64-bit support"

HOMEPAGE = https://www.tcl.tk
LICENSE = Custom

SERVICE_SETUP = src/service-setup.sh

include ../../mk/spksrc.spk.mk

