SPK_NAME = jdupes
SPK_VERS = 1.28.0
SPK_REV = 1
SPK_ICON = src/jdupes.png

DEPENDS = cross/jdupes

MAINTAINER = jbruchon
DESCRIPTION = A powerful duplicate file finder and an enhanced fork of fdupes.
STARTABLE = no

HOMEPAGE = https://github.com/jbruchon/jdupes/
LICENSE = MIT

SPK_COMMANDS = bin/jdupes

include ../../mk/spksrc.spk.mk
