SPK_NAME = jdupes
SPK_VERS = 1.31.2
SPK_REV = 1
SPK_ICON = src/jdupes.png

DEPENDS = cross/jdupes

MAINTAINER = SynoCommunity
DESCRIPTION = A powerful duplicate file finder and an enhanced fork of fdupes.
STARTABLE = no

HOMEPAGE = https://www.jodybruchon.com/software/#jdupes
LICENSE = MIT

SPK_COMMANDS = bin/jdupes

include ../../mk/spksrc.spk.mk
