PKG_NAME = pyextdirect
PKG_VERS = 0.2
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = http://pypi.python.org/packages/source/p/$(PKG_NAME)/
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS =

HOMEPAGE = http://pypi.python.org/pypi/pyextdirect
COMMENT  = Python implementation of Ext Direct
LICENSE  =

include ../../mk/spksrc.python-module.mk

