SPK_NAME = irssi
SPK_VERS = 1.2.3
SPK_REV = 3
SPK_ICON = src/irssi.png

DEPENDS = cross/irssi

MAINTAINER = SynoCommunity
DESCRIPTION = Irssi is a terminal based IRC client for UNIX systems. It also supports SILC and ICB protocols via plugins.
DISPLAY_NAME = Irssi
STARTABLE = no
CHANGELOG = "1. Update irssi to v1.2.3 released on 2021-04-11.<br/>2. Update openssl to 1.1.1k.<br/>3. Update glib to 2.66."

HOMEPAGE = https://www.irssi.org/
LICENSE = GPLv2

SERVICE_SETUP = src/service-setup.sh

SPK_COMMANDS = bin/irssi

include ../../mk/spksrc.spk.mk
