SPK_NAME = irssi
SPK_VERS = 0.8.17
SPK_REV = 1
SPK_ICON = src/irssi.png

DEPENDS = cross/irssi

MAINTAINER = SynoCommunity
DESCRIPTION = Irssi is a terminal based IRC client for UNIX systems. It also supports SILC and ICB protocols via plugins.
DISPLAY_NAME = Irssi
STARTABLE = no
BETA = 1

HOMEPAGE = http://www.irssi.org/
LICENSE = GPLv2
HELP_URL = https://irssi.org/documentation/

INSTALLER_SCRIPT = src/installer.sh
SSS_SCRIPT       = src/dsm-control.sh

INSTALL_PREFIX = /usr/local/$(SPK_NAME)

include ../../mk/spksrc.spk.mk
