
GITEA="${SYNOPKG_PKGDEST}/bin/gitea"
ENV="HOME=${SYNOPKG_PKGHOME} GITEA_CUSTOM=${SYNOPKG_PKGVAR}/custom GITEA_WORK_DIR=${SYNOPKG_PKGVAR}"
SERVICE_COMMAND="env ${ENV} ${GITEA} web --port 8418 --config ${SYNOPKG_PKGVAR}/config.ini --pid ${PID_FILE}"
SVC_BACKGROUND=y
