TC_ARCH = hi3535
TC_VERS = 6.1
TC_KERNEL = 3.4.35+

TC_DIST = hi3535-gcc483_glibc219_hi3535-GPL
TC_DIST_SITE = https://sourceforge.net/projects/dsgpl/files/Tool%20Chain/DSM%206.1%20Tool%20Chains/HiSilicon%20Hi3535%20Linux%203.4.35

TC_TARGET = arm-cortexa9-linux-gnueabi
TC_SYSROOT = $(TC_TARGET)/sysroot

include ../../mk/spksrc.tc.mk
