PKG_NAME = configobj
PKG_VERS = 4.7.2
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = http://pypi.python.org/packages/source/c/$(PKG_NAME)
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS =

HOMEPAGE = http://pypi.python.org/pypi/configobj
COMMENT  = Config file reading, writing and validation
LICENSE  =

include ../../mk/spksrc.python-module.mk

