TK_NAME = syno-armv7

# generic toolkit for arm7hf DSM
TK_ARCH = alpine alpine4k armada370 armada375 armada38x armadaxp comcerto2k monaco
TK_VERS = 7.2

TK_DIST = armada38x

TK_TARGET = arm-unknown-linux-gnueabi
TK_SYSROOT = $(TK_TARGET)/sysroot

include ../../mk/spksrc.toolkit.mk
