SPK_NAME = lm-sensors
SPK_VERS = 3.6.0
SPK_REV = 1

DEPENDS = cross/lm-sensors

SPK_DEPENDS = Perl

MAINTAINER = hgy59
DESCRIPTION = lm-sensors provides user-space support for the hardware monitoring drivers in Linux 2.6.5 and later.
DISPLAY_NAME = lm-sensors
STARTABLE = no

HOMEPAGE = https://hwmon.wiki.kernel.org/
LICENSE = GPLv2

SPK_COMMANDS = bin/sensors bin/sensors-conf-convert sbin/fancontrol sbin/sensors-detect

include ../../mk/spksrc.spk.mk
