--- Makefile.orig	2015-03-30 12:52:37.000000000 +0200
+++ Makefile	2015-03-30 12:52:57.000000000 +0200
@@ -87,7 +87,7 @@
 $(foreach V,$(SUBDIR_VARS),$(eval $(call RESET,$(V))))
 SUBDIR := $(1)/
 include $(SRC_PATH)/$(1)/Makefile
--include $(SRC_PATH)/$(1)/$(ARCH)/Makefile
+-include $(SRC_PATH)/$(1)/$(FFMPEG_ARCH)/Makefile
 include $(SRC_PATH)/library.mak
 endef
 
