PKG_NAME = PyYAML
PKG_VERS = 3.11
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = https://files.pythonhosted.org/packages/source/P/$(PKG_NAME)
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS = cross/libyaml

HOMEPAGE = http://pyyaml.org/
COMMENT  = PyYAML is a YAML parser and emitter for the Python programming language
LICENSE  = MIT

include ../../mk/spksrc.python-module.mk
