SPK_NAME = stockfish-fishnet
SPK_VERS = 180120

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = Guillaume
DESCRIPTION = Stockfish for Lichess is the engine used on the website to play against player and is used on contributed remote servers for games analysis
DISPLAY_NAME = Stockfish for Lichess
STARTABLE=no
HOMEPAGE = https://github.com/niklasf/Stockfish
LICENSE  = GPLv2/GPLv3

include ../../mk/spksrc.spk.mk
