PKG_NAME = cffi
PKG_VERS = 0.8.6
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = http://pypi.python.org/packages/source/c/$(PKG_NAME)
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS = cross/libffi cross/pycparser

HOMEPAGE = http://pypi.python.org/pypi/cffi
COMMENT  = Foreign Function Interface for Python calling C code
LICENSE  =

include ../../mk/spksrc.python-module.mk
