TC_ARCH = rtd1619b
TC_VERS = 7.2
TC_KERNEL = 5.10.55
TC_GLIBC = 2.36

TC_DIST = rtd1619b-gcc1220_glibc236_armv8-GPL
TC_DIST_SITE_PATH = Realtek%20RTD16xxb%20Linux%205.10.55

TC_TARGET = aarch64-unknown-linux-gnu
TC_SYSROOT = $(TC_TARGET)/sysroot

include ../../mk/spksrc.tc.mk
