PKG_NAME = distribute
PKG_VERS = 0.6.35
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = http://pypi.python.org/packages/source/d/$(PKG_NAME)
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS =

HOMEPAGE = http://pypi.python.org/pypi/distribute
COMMENT  = Easily download, build, install, upgrade, and uninstall Python packages
LICENSE  =

include ../../mk/spksrc.python-module.mk
