SPK_NAME = links
SPK_VERS = 2.21
SPK_REV = 2
SPK_ICON = src/links.png

DEPENDS = cross/links

MAINTAINER = SynoCommunity
DESCRIPTION = Links is a web browser running in text mode.
DISPLAY_NAME = Links
STARTABLE = no
CHANGELOG = "1. Update links to 2.21.<br/>2. Update openssl to 1.1."

HOMEPAGE = http://links.twibright.com/
LICENSE = GPLv2

SPK_COMMANDS = bin/links

include ../../mk/spksrc.spk.mk
