SPK_NAME = links
SPK_VERS = 2.28
SPK_REV = 1
SPK_ICON = src/links.png

DEPENDS = cross/links

MAINTAINER = SynoCommunity
DESCRIPTION = Links is a web browser running in text mode.
DISPLAY_NAME = Links
STARTABLE = no

HOMEPAGE = http://links.twibright.com/
LICENSE = GPLv2

SPK_COMMANDS = bin/links

include ../../mk/spksrc.spk.mk
