SPK_NAME = ffmpeg-videostation
SPK_VERS = 1.0.0
SPK_REV = 1

SPK_DEPENDS = "ffmpeg>=4.2"

MAINTAINER = ymartin59
DESCRIPTION = ""
DISPLAY_NAME = ffmeg-videostation

CHANGELOG = "Initial revision"

HOMEPAGE   = http://
LICENSE    = GPL

SSS_SCRIPT = src/dsm-control.sh
STARTABLE = no

# Non arch specific
override ARCH=

include ../../mk/spksrc.spk.mk
