PKG_NAME = mpfr
PKG_VERS = 3.1.2
PKG_EXT = tar.bz2
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = http://www.mpfr.org/mpfr-$(PKG_VERS)
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS =

HOMEPAGE = http://www.mpfr.org
COMMENT  = Multiple-precision floating-point computations with correct rounding
LICENSE  = LGPL


GNU_CONFIGURE = 1


include ../../mk/spksrc.native-cc.mk
