SPK_NAME = fossil-scm
SPK_VERS = 2.10
SPK_REV = 1
SPK_ICON = src/fossil-scm.png

DEPENDS = cross/fossil-scm

MAINTAINER = SynoCommunity
DISPLAY_NAME = Fossil SCM

DESCRIPTION = "Fossil is a simple, high-reliability, distributed software configuration management system."
STARTABLE = no
CHANGELOG = "Initial version."

HOMEPAGE = https://www.fossil-scm.org/
LICENSE  = BSD2

SPK_COMMANDS  = bin/fossil

include ../../mk/spksrc.spk.mk
