PKG_NAME = libmad
PKG_VERS = 0.15.1b
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = http://downloads.sourceforge.net/project/mad/$(PKG_NAME)/$(PKG_VERS)
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS =

MAINTAINER=	http://packages.nas-forum.com/
HOMEPAGE=	http://www.underbit.com/products/mad/
COMMENT=	High-quality fixed-point MPEG audio decoder with 24-bit output
LICENSE=	GPL

GNU_CONFIGURE = 1

include ../../mk/spksrc.cross-cc.mk

