
TC_NAME = syno-cedarview

TC_DIST_NAME = gcc421_glibc236_x86_cedarview-GPL.tgz

TC_EXT = tgz
TC_DIST_SITE = http://sourceforge.net/projects/dsgpl/files/DSM%204.0%20Tool%20Chains/Intel%20x86%20Linux%202.6.32%20%28Cedarview%29

TC_BASE_DIR = i686-linux-gnu
TC_PREFIX = i686-linux-gnu
TC_TARGET = i686-linux-gnu

TC_CFLAGS =
TC_LDFLAGS =

include ../../mk/spksrc.tc.mk
