SPK_NAME = nano
SPK_VERS = 6.3
SPK_REV = 8
SPK_ICON = src/nano.png

DEPENDS = cross/nano

MAINTAINER = SynoCommunity
DESCRIPTION = nano is a text editor for Unix-like computing systems or operating environments using a command line interface.
DESCRIPTION_GER = nano ist ein einfacher Editor, der die Bearbeitung von Dateien in einem Terminal bzw. auf der Konsole erlaubt.
STARTABLE = no

HOMEPAGE   = http://www.nano-editor.org
LICENSE    = GPLv2

SERVICE_SETUP = src/service-setup.sh

SPK_COMMANDS = bin/nano bin/rnano

include ../../mk/spksrc.spk.mk
