SPK_NAME = htop
SPK_VERS = 2.2.0
SPK_REV = 2
SPK_ICON = src/htop.png

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = hgy59
DESCRIPTION = Interactive text-mode process viewer for Unix systems. The package is intended for DSM-5.0 or earlier where it\'s not available.
DISPLAY_NAME = htop
STARTABLE = no
CHANGELOG = "1. Update to version 2.2.0<br/>2. Activate unicode support"

HOMEPAGE   = http://hisham.hm/htop/
LICENSE    = GPLv2

SPK_COMMANDS = bin/htop


include ../../mk/spksrc.spk.mk
