SPK_NAME = htop
SPK_VERS = 3.3.0
SPK_REV = 1
SPK_ICON = src/htop.png

DEPENDS = cross/htop

MAINTAINER = hgy59
DESCRIPTION = Interactive text-mode process viewer for Unix systems. The package is intended for DSM 5.0 or earlier where it\'s not available.
DISPLAY_NAME = htop
STARTABLE = no

HOMEPAGE = http://hisham.hm/htop/
LICENSE = GPLv2+

SPK_COMMANDS = bin/htop

include ../../mk/spksrc.spk.mk
