SPK_NAME = rhash
SPK_VERS = 1.3.5
SPK_REV = 1

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = Fredrike
DESCRIPTION = "RHash is a console utility for calculation and verification of magnet links and a wide range of hash sums like CRC32, MD4, MD5, SHA1, SHA256, SHA512, SHA3, AICH, ED2K, Tiger, DC++ TTH, BitTorrent BTIH, GOST R 34.11-94, RIPEMD-160, HAS-160, EDON-R, Whirlpool and Snefru."
RELOAD_UI = no
DISPLAY_NAME = rhash
STARTABLE = no

HOMEPAGE   = http://rhash.sourceforge.net/
LICENSE    = MIT

INSTALLER_SCRIPT = src/installer.sh

INSTALL_PREFIX = /usr/local/$(SPK_NAME)

include ../../mk/spksrc.spk.mk

