
PKG_NAME = libtool
PKG_VERS = 2.4.2
PKG_EXT = tar.gz
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)
PKG_DIST_NAME = $(PKG_DIR).$(PKG_EXT)
PKG_DIST_SITE = http://ftp.gnu.org/gnu/$(PKG_NAME)

DEPENDS =

MAINTAINER=	http://packages.nas-forum.com/
HOMEPAGE=	http://www.gnu.org/s/bison/
COMMENT=	General-purpose parser generator
LICENSE=	GNU GPL

GNU_CONFIGURE = 1

include ../../mk/spksrc.cross-cc.mk
