PKG_NAME = check
PKG_VERS = 0.15.2
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = https://github.com/libcheck/check/releases/download/$(PKG_VERS)
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS =

HOMEPAGE = https://libcheck.github.io/check/
COMMENT  = A unit testing framework for C
LICENSE  = LGPLv2.1

GNU_CONFIGURE = 1

include ../../mk/spksrc.cross-cc.mk
