SPK_NAME = ruby
SPK_VERS = 3.0.0
SPK_REV = 7
SPK_ICON = src/ruby.png

DEPENDS = cross/$(SPK_NAME)

CHANGELOG = "Restore package and update to v3.3.0, due to the fact that Synology retired Ruby v2.4.3-0067."

MAINTAINER = SynoCommunity
DESCRIPTION = Ruby Programming Language.
DESCRIPTION_FRE = Langage de programmation Ruby.
DESCRIPTION_SPN = Lenguaje de programación Ruby.
STARTABLE = no
DISPLAY_NAME = Ruby

HOMEPAGE = http://www.ruby-lang.org/
LICENSE  = 2-clause BSDL

SPK_COMMANDS  = bin/bundle bin/bundler bin/erb bin/gem bin/irb bin/racc
SPK_COMMANDS += bin/rake bin/rbs bin/rdoc bin/ri bin/ruby bin/typeprof

include ../../mk/spksrc.spk.mk
