PKG_NAME = ujson
PKG_VERS = 4.2.0
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = https://files.pythonhosted.org/packages/source/u/$(PKG_NAME)
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS =

HOMEPAGE = https://github.com/ultrajson/ultrajson
COMMENT  = Ultra fast JSON decoder and encoder written in C with Python bindings.
LICENSE  = https://github.com/ultrajson/ultrajson/blob/main/LICENSE.txt

include ../../mk/spksrc.python-wheel.mk
