SPK_NAME = libtree
SPK_VERS = 3.1.1
SPK_REV = 1

DEPENDS = cross/libtree

MAINTAINER = SynoCommunity
DESCRIPTION = A tool that turns ldd into a tree and explains how shared libraries are found or why they cannot be located.
DISPLAY_NAME = libtree
STARTABLE = no

HOMEPAGE = https://github.com/haampie/libtree
LICENSE = MIT

SPK_COMMANDS = bin/libtree

include ../../mk/spksrc.spk.mk
