KERNEL_ARCH = x86
KERNEL_VERS = 6.2.2
KERNEL_BUILD = 24922
KERNEL_DIST = linux-3.10.x
KERNEL_URL_DIR = x64-source
KERNEL_CONFIG = synoconfigs/x86_64
KERNEL_BASE_ARCH = x86

include ../../mk/spksrc.kernel.mk
