SPK_NAME = tekkitlite
SPK_VERS = 0.6.1
SPK_REV = 8
SPK_ICON = tekkit.png
DSM_UI_DIR = dsm

DEPENDS  =
SPK_DEPENDS =

MAINTAINER = SynoCommunity
DESCRIPTION = A new Tekkit is here! One geared for smaller servers and that takes avantage of the new way Minecraft handles multiplayer and arising out of the chaos that is the forgebukkit fiasco, we present Tekkit Lite.
ADMIN_PORT = 
RELOAD_UI = yes
DISPLAY_NAME = Tekkit Lite
BETA = 

HOMEPAGE   = http://technicpack.net/
LICENSE    = GPL

WIZARDS_DIR = src/wizard/

INSTALLER_SCRIPT = src/installer.sh
SSS_SCRIPT       = src/dsm-control.sh

INSTALL_PREFIX = /usr/local/$(SPK_NAME)

COPY_TARGET = 
POST_STRIP_TARGET = 

# Pure Java package, make sure ARCH is not defined
override ARCH=

include ../../mk/spksrc.spk.mk
