SPK_NAME = ms-edit
SPK_VERS = 2.0.0
SPK_REV = 1

UNSUPPORTED_ARCHS = $(ARMv5_ARCHS) $(PPC_ARCHS)

DEPENDS = cross/ms-edit

MAINTAINER = SynoCommunity
DESCRIPTION = A simple editor for simple needs.
DISPLAY_NAME = edit
STARTABLE = no

HOMEPAGE = https://github.com/microsoft/edit/
LICENSE = MIT

SPK_COMMANDS = bin/edit

include ../../mk/spksrc.spk.mk
