#!/bin/sh

# Package
PACKAGE="haproxy"
DNAME="HAProxy"

# Others
INSTALL_DIR="/usr/local/${PACKAGE}"
PATH="${INSTALL_DIR}/bin:/usr/local/bin:/bin:/usr/bin:/usr/syno/bin"
HAPROXY="${INSTALL_DIR}/bin/haproxy"
CFG_FILE="${INSTALL_DIR}/var/haproxy.conf"
PID_FILE="${INSTALL_DIR}/var/haproxy.pid"

start_daemon ()
{
    PATH=${PATH} ${HAPROXY} -f ${CFG_FILE} -p ${PID_FILE} -D
}

stop_daemon ()
{
    kill `cat ${PID_FILE}`
    wait_for_status 1 20
    rm -f ${PID_FILE}
}

daemon_status ()
{
    if [ -f ${PID_FILE} ] && [ -d /proc/`cat ${PID_FILE}` ]; then
        return 0
    fi
    return 1
}

wait_for_status()
{
    counter=$2
    while [ ${counter} -gt 0 ]; do
        daemon_status
        [ $? -eq $1 ] && break
        let counter=counter-1
        sleep 1
    done
}

case $1 in
    start)
        if daemon_status; then
            echo ${DNAME} is already running
            exit 0
        else
            echo Starting ${DNAME} ...
            cd ${INSTALL_DIR}/var
            perl genConf.pl
            start_daemon
            exit $?
        fi
        ;;
    stop)
        if daemon_status; then
            echo Stopping ${DNAME} ...
            stop_daemon
            exit $?
        else
            echo ${DNAME} is not running
            exit 0
        fi
        ;;
    status)
        if daemon_status; then
            echo ${DNAME} is running
            exit 0
        else
            echo ${DNAME} is not running
            exit 1
        fi
        ;;
    check)
        cd ${INSTALL_DIR}/var
        perl genConf.pl
        PATH=${PATH} ${HAPROXY} -f ${CFG_FILE} -c
        exit $?
        ;;
    restart)
        cd ${INSTALL_DIR}/var
        perl genConf.pl
        PATH=${PATH} ${HAPROXY} -f ${CFG_FILE} -c
        if [ $? -eq 0 ]; then
            if daemon_status; then
                echo Stopping ${DNAME} ...
                stop_daemon
            else
                echo ${DNAME} is not running
            fi
            sleep 3
            if daemon_status; then
                echo ${DNAME} is already running
            else
                echo Starting ${DNAME} ...
                start_daemon
            fi
        else
            echo Restarting ${DNAME} : aborted
        fi
        ;;
    log)
        echo ${LOG_FILE}
        exit 0
        ;;
    *)
        exit 1
        ;;
esac

