SPK_NAME = subversion
SPK_VERS = 1.7.8
SPK_REV = 1
SPK_ICON = src/subversion.png
BETA = 1

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = SynoCommunity
DESCRIPTION = Subversion is an open source centralized version control system.
DESCRIPTION_FRE = Subversion est un logiciel de gestion de versions centralisée open source.
STARTABLE = no
DISPLAY_NAME = Subversion

HOMEPAGE = http://subversion.apache.org/
LICENSE  =

INSTALLER_SCRIPT = src/installer.sh
SSS_SCRIPT       = src/dsm-control.sh
ADDITIONAL_SCRIPTS =

INSTALL_PREFIX = /usr/local/$(SPK_NAME)

include ../../mk/spksrc.spk.mk
