SPK_NAME = sshfs
SPK_VERS = 3.6.0
SPK_REV = 3
SPK_ICON = src/sshfs.png

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = SynoCommunity
DESCRIPTION = sshfs is a filesystem client based on the SSH File Transfer Protocol
DISPLAY_NAME = sshfs
STARTABLE = no
CHANGELOG = "Update to version 3.6.0"
BETA = 1

HOMEPAGE   = https://github.com/libfuse/sshfs
LICENSE    = GPLv2, LGPLv2.1 (libfuse.so, libulockmgr.so)

SERVICE_SETUP = src/service-setup.sh

include ../../mk/spksrc.spk.mk

