SPK_NAME = sshfs
SPK_VERS = 2.10
SPK_REV = 1

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = SynoCommunity
DESCRIPTION = sshfs is a network filesystem client to connect to SSH servers
CHANGELOG = "Initial release"
DISPLAY_NAME = sshfs
STARTABLE = no

HOMEPAGE = https://github.com/libfuse/sshfs
LICENSE = GPLv2

SPK_COMMANDS = bin/sshfs


include ../../mk/spksrc.spk.mk
