SPK_NAME = sd
SPK_VERS = 0.7.6
SPK_REV = 1

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = SynoCommunity
DESCRIPTION = Intuitive find & replace CLI (sed alternative).
STARTABLE = no

HOMEPAGE = https://github.com/chmln/sd#readme
LICENSE  = MIT

SPK_COMMANDS = bin/sd

include ../../mk/spksrc.spk.mk
