include ../../cross/libapparmor/apparmor.info.mk

PKG_VERS = $(AA_PKG_VERS)
PKG_EXT = $(AA_PKG_EXT)
PKG_DIST_NAME = $(AA_PKG_DIST_NAME)
PKG_DIST_SITE = $(AA_PKG_DIST_SITE)
PKG_DIR = $(AA_PKG_DIR)

HOMEPAGE = $(AA_HOMEPAGE)

UNSUPPORTED_ARCHS = $(AA_UNSUPPORTED_ARCHS)
