SPK_NAME = restic
SPK_VERS = 0.18.1
SPK_REV = 1
SPK_ICON = src/restic.png

MAINTAINER = krombel
DISPLAY_NAME = restic
DESCRIPTION  = restic is a cli command for backups.
HOMEPAGE = https://restic.net/
CHANGELOG = "1. Initial build."

LICENSE = BSD-2-clause

DEPENDS = cross/restic

STARTABLE = no

SPK_COMMANDS = bin/restic

include ../../mk/spksrc.spk.mk
