SPK_NAME = restic
SPK_VERS = 0.19.1
SPK_REV = 2
SPK_ICON = src/logo.png

DEPENDS = cross/restic

MAINTAINER = fgma
DESCRIPTION = Restic is a fast and secure backup program.
DISPLAY_NAME = restic
STARTABLE = no

CHANGELOG = "Update restic to 0.19.1 (<a target=\"_blank\" href=\"https://github.com/restic/restic/releases/tag/v0.19.1\">Changelog</a>)"

HOMEPAGE = https://restic.net/
LICENSE  = BSD 2-Clause License
LICENSE_FILE = $(WORK_DIR)/$(SPK_NAME)/LICENSE

SPK_COMMANDS = bin/restic

include ../../mk/spksrc.spk.mk
