TC_ARCH = armada37xx
TC_VERS = 6.2.2
TC_KERNEL = 4.4.59+

TC_DIST = armada37xx-gcc494_glibc220_armv8-GPL
TC_DIST_SITE = https://sourceforge.net/projects/dsgpl/files/Tool%20Chain/DSM%206.2.2%20Tool%20Chains/Marvell%20Armada%2037xx%20Linux%204.4.59

TC_PREFIX = aarch64-unknown-linux-gnueabi
TC_SYSROOT = $(TC_PREFIX)/sysroot

include ../../mk/spksrc.tc.mk
