PKG_NAME = libutempter
PKG_VERS = 1.2.1
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = http://ftp.altlinux.org/pub/people/ldv/utempter/
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS =

HOMEPAGE = https://github.com/altlinux/libutempter
COMMENT  = libutempter provides a library interface for terminal emulators such as screen and xterm to record user sessions to utmp and wtmp files.
LICENSE  = LGPLv2.1

CONFIGURE_TARGET = nop

include ../../mk/spksrc.cross-cc.mk
