###############################################################################
# spksrc.toolchain/tc-normalize.mk
#
# Applies post-extraction normalization to the toolchain sysroot.
#
# This file:
#  - normalizes libtool (*.la) files generated by Synology toolchains
#  - rewrites embedded libdir paths to point to the local WORK_DIR sysroot
#
# Targets:
#  normalize_msg_target
#  pre_normalize_target    (override with PRE_NORMALIZE_TC_TARGET)
#  normalize_target        (override with NORMALIZE_TC_TARGET)
#  post_normalize_target   (override with POST_NORMALIZE_TC_TARGET)
#
# Variables:
#  NORMALIZE_COOKIE  : Status cookie indicating normalize completion
#
# Notes:
#  - Required for correct linkage during cross-compilation
#  - Idempotent via status cookie
#
###############################################################################

NORMALIZE_COOKIE = $(WORK_DIR)/.$(COOKIE_PREFIX)normalize_done

ifeq ($(strip $(PRE_NORMALIZE_TC_TARGET)),)
PRE_NORMALIZE_TC_TARGET = pre_normalize_target
else
$(PRE_NORMALIZE_TC_TARGET): normalize_msg
endif
ifeq ($(strip $(NORMALIZE_TC_TARGET)),)
NORMALIZE_TC_TARGET = normalize_target
else
$(NORMALIZE_TC_TARGET): $(PRE_NORMALIZE_TC_TARGET)
endif
ifeq ($(strip $(POST_NORMALIZE_TC_TARGET)),)
POST_NORMALIZE_TC_TARGET = post_normalize_target
else
$(POST_NORMALIZE_TC_TARGET): $(NORMALIZE_TC_TARGET)
endif

.PHONY: normalize normalize_msg
.PHONY: $(PRE_NORMALIZE_TC_TARGET) $(NORMALIZE_TC_TARGET) $(POST_NORMALIZE_TC_TARGET)

normalize_msg:
	@$(MSG) "Normalizing libtool files for $(NAME)"

pre_normalize_target: normalize_msg

normalize_target:  $(PRE_NORMALIZE_TC_TARGET)
	chmod -R u+w $(WORK_DIR)
	@find $(WORK_DIR)/$(TC_TARGET) -type f -name '*.la' -exec sed -i -e "s|^libdir=.*$$|libdir='$(WORK_DIR)/$(TC_TARGET)/$(TC_LIBRARY)'|" {} \;

post_normalize_target: $(NORMALIZE_TC_TARGET)

ifeq ($(wildcard $(NORMALIZE_COOKIE)),)
normalize: $(NORMALIZE_COOKIE)

$(NORMALIZE_COOKIE): $(POST_NORMALIZE_TC_TARGET)
	$(create_target_dir)
	@touch -f $@
else
normalize: ;
endif
