PKG_NAME = mono
PKG_VERS = 3.4.0
PKG_EXT = tar.bz2
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = http://download.mono-project.com/sources/mono
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS = 

HOMEPAGE   = http://www.mono-project.com/
COMMENT    = .NET for linux... dude
LICENSE    =

GNU_CONFIGURE = 1
CONFIGURE_ARGS = 

include ../../mk/spksrc.native-cc.mk
