TC_NAME = syno-$(TC_ARCH)

TC_ARCH = evansport
TC_VERS = 4.3
TC_FIRMWARE = 3.1-1594

TC_DIST = gcc463_glibc213_i686-GPL
TC_EXT = tgz
TC_DIST_NAME = $(TC_DIST).$(TC_EXT)
TC_DIST_SITE = https://sourceforge.net/projects/dsgpl/files/Tool%20Chain/DSM%204.3%20Tool%20Chains/Intel%20x86%20Linux%203.2.40%20%28Evansport%29

TC_PREFIX = i686-pc-linux-gnu
TC_TARGET = i686-pc-linux-gnu

TC_CFLAGS =
TC_CPPFLAGS =
TC_CXXFLAGS =
TC_LDFLAGS =

TC_SYSROOT = $(TC_PREFIX)

include ../../mk/spksrc.tc.mk
