PKG_NAME = psutil
PKG_VERS = 0.6.1
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = http://$(PKG_NAME).googlecode.com/files
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS =

HOMEPAGE = http://pypi.python.org/pypi/psutil
COMMENT  = A process and system utilities module for Python
LICENSE  =  BSD License

include ../../mk/spksrc.python-module.mk
