SPK_NAME = nmap
SPK_VERS = 7.80
SPK_REV = 1
SPK_ICON = src/nmap.png

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = SynoCommunity
DESCRIPTION = Nmap ("Network Mapper") is a free and open source utility for network discovery and security auditing
DISPLAY_NAME = nmap
STARTABLE = no

HOMEPAGE = https://nmap.org/
LICENSE  = https://svn.nmap.org/nmap/COPYING

SPK_COMMANDS = bin/nmap bin/nping bin/ndiff


include ../../mk/spksrc.spk.mk
