PKG_NAME = cmake
PKG_VERS = 3.19.1
PKG_EXT = tar.gz
PKG_DIST_NAME = v$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = https://github.com/Kitware/CMake/archive
PKG_DIST_FILE = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIR = CMake-$(PKG_VERS)

DEPENDS = 

HOMEPAGE = https://cmake.org/
COMMENT  = CMake is an open-source, cross-platform family of tools designed to build, test and package software.
LICENSE  = OSI-approved BSD 3-Clause License

GNU_CONFIGURE = 1

include ../../mk/spksrc.native-cc.mk
