SPK_NAME = mg
SPK_VERS = 3.5
SPK_REV = 2
SPK_ICON = src/unix.png

DEPENDS = cross/mg

MAINTAINER = SynoCommunity
DESCRIPTION = Micro \(GNU\) Emacs-like text editor.

DISPLAY_NAME = "mg (micro gnu)"
STARTABLE = no

HOMEPAGE = https://man.troglobit.com/man1/mg.1.html
LICENSE  = UNLICENSE

SPK_COMMANDS = bin/mg

include ../../mk/spksrc.spk.mk
