TC_NAME = syno-x64

TC_ARCH = x86_64 bromolow cedarview avoton
TC_VERS = 4.3
TC_FIRMWARE = 3.1-1594
TC_KERNEL = 3.2.40
TC_GCC = 4.2.0
TC_GLIBC = 2.3.6

TC_DIST = gcc420_glibc236_x64-GPL
TC_EXT = tgz
TC_DIST_SITE_PATH = Intel%20x86%20Linux%203.2.40%20%28Pineview%29

TC_TARGET = x86_64-linux-gnu
TC_SYSROOT = $(TC_TARGET)/sys-root

include ../../mk/spksrc.tc.mk
