TC_ARCH = 88f6281
TC_VERS = 4.3
TC_FIRMWARE = 3.1-1594
TC_KERNEL = 2.6.32
TC_GCC = 4.2.1
TC_GLIBC = 2.5

TC_DIST = gcc421_glibc25_88f6281-GPL
TC_EXT = tgz
TC_DIST_SITE_PATH = Marvell%2088F628x%20Linux%202.6.32

TC_TARGET = arm-none-linux-gnueabi
TC_SYSROOT = $(TC_TARGET)/libc
TC_LIBRARY = $(TC_SYSROOT)/usr/lib

include ../../mk/spksrc.tc.mk
