SPK_NAME = alsa-utils
SPK_VERS = 1.2.9
SPK_REV = 1

DEPENDS = cross/alsa-utils

UNSUPPORTED_ARCHS = $(OLD_PPC_ARCHS)

MAINTAINER = SynoCommunity
DESCRIPTION = Advanced Linux Sound Architecture provides audio and MIDI functionality to the Linux operating system.
STARTABLE = no

HOMEPAGE = https://www.alsa-project.org/
LICENSE = GPLv2

SPK_COMMANDS  = bin/aconnect
SPK_COMMANDS += bin/alsabat
SPK_COMMANDS += bin/alsaloop
SPK_COMMANDS += bin/alsamixer
SPK_COMMANDS += bin/alsatplg
SPK_COMMANDS += bin/alsaucm
SPK_COMMANDS += bin/amidi
SPK_COMMANDS += bin/amixer
SPK_COMMANDS += bin/aplay
SPK_COMMANDS += bin/aplaymidi
SPK_COMMANDS += bin/arecord
SPK_COMMANDS += bin/arecordmidi
SPK_COMMANDS += bin/aseqdump
SPK_COMMANDS += bin/aseqnet
SPK_COMMANDS += bin/axfer
SPK_COMMANDS += bin/iecset
SPK_COMMANDS += bin/speaker-test

include ../../mk/spksrc.spk.mk
