PKG_NAME = tornado
PKG_VERS = 4.0.1
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = https://files.pythonhosted.org/packages/source/t/$(PKG_NAME)
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS =

HOMEPAGE = http://www.tornadoweb.org/
COMMENT  = Tornado is a Python web framework and asynchronous networking library, originally developed at FriendFeed. 
LICENSE  = Apache 2.0

include ../../mk/spksrc.python-wheel.mk
