PKG_NAME = tornado
PKG_VERS = 2.2
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = http://github.com/downloads/facebook/$(PKG_NAME)
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS =

HOMEPAGE   = http://www.tornadoweb.org/
COMMENT    = Open source scalable, non-blocking web server and tools
LICENSE    = http://www.apache.org/licenses/LICENSE-2.0.html

include ../../mk/spksrc.python-module.mk

