PKG_NAME = testdisk
PKG_VERS = 7.0
PKG_EXT = tar.bz2
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = http://www.cgsecurity.org
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS = cross/ncurses cross/libuuid

HOMEPAGE = http://www.cgsecurity.org/wiki/TestDisk
COMMENT  = TestDisk is powerful free data recovery software

GNU_CONFIGURE = 1

include ../../mk/spksrc.cross-cc.mk
