SPK_NAME = nodejs_v22
SPK_VERS = 22.14.0
SPK_REV = 1
SPK_ICON = src/node.png

DEPENDS = cross/nodejs_v22

REQUIRED_MIN_DSM = 7.2

MAINTAINER = SynoCommunity
DESCRIPTION = Node.js is an open-source, cross-platform JavaScript runtime environment.
CHANGELOG = "Initial release of Node.js® v22"
DISPLAY_NAME = Node.js® v22

HOMEPAGE = https://nodejs.org
LICENSE  = https://raw.githubusercontent.com/nodejs/node/refs/heads/main/LICENSE

STARTABLE = no

SPK_COMMANDS = bin/node bin/npm bin/npx

include ../../mk/spksrc.spk.mk
