
PKG_NAME = dotconf
PKG_VERS = 1.0.13
PKG_EXT = tar.gz
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = http://www.azzit.de/$(PKG_NAME)/download/v1.0

DEPENDS = 

MAINTAINER = http://packages.nas-forum.com
HOMEPAGE   = http://www.azzit.de/dotconf/
COMMENT    = Configuration file parse
LICENSE    = 

GNU_CONFIGURE = 1
 
include ../../mk/spksrc.cross-cc.mk
