SPK_NAME = memaslap
SPK_VERS = 1.0
SPK_REV = 1

DEPENDS = cross/libmemcached

MAINTAINER = SynoCommunity
DESCRIPTION = memaslap is a load generation and benchmark tool for memcached servers. It generates configurable workload such as threads, concurrencies, connections, run time, overwrite, miss rate, key size, value size, get/set proportion, expected throughput, and so on.
STARTABLE = no

HOMEPAGE = http://docs.libmemcached.org/bin/memaslap.html
LICENSE = 3-Clause BSD

SPK_COMMANDS = bin/memaslap

include ../../mk/spksrc.spk.mk
