SPK_NAME = ariang
SPK_VERS = 1.3.7
SPK_REV = 1
SPK_ICON = src/ariang.png
DSM_UI_DIR = app

DEPENDS = cross/ariang

SPK_DEPENDS = "WebStation>=2.1.0"

MAINTAINER = vitkabele
DESCRIPTION = AriaNg, a modern web frontend making aria2 easier to use.
ADMIN_URL = /ariang/
DISPLAY_NAME = AriaNg

HOMEPAGE = https://ariang.mayswind.net/
LICENSE  = MIT

CONF_DIR = src/conf
STARTABLE = no

# Pure PHP package, make sure ARCH is noarch
override ARCH=noarch

include ../../mk/spksrc.spk.mk
