SPK_NAME = inetutils
SPK_VERS = 2.5
SPK_REV = 1

DEPENDS = cross/inetutils

MAINTAINER = SynoCommunity
DESCRIPTION = GNU network utilities.
STARTABLE = no

HOMEPAGE = https://www.gnu.org/software/inetutils/
LICENSE = GPLv3

SPK_COMMANDS = bin/telnet bin/whois

include ../../mk/spksrc.spk.mk
