
TC_NAME = syno-x86

TC_DIST_NAME = gcc420_glibc236_pineview.tgz

TC_EXT = tgz
TC_DIST_SITE = http://sourceforge.net/projects/dsgpl/files/DSM%203.1%20Tool%20Chains/Intel%20x86%20Linux%202.6.32

TC_BASE_DIR = i686-linux-gnu
TC_PREFIX = i686-linux-gnu
TC_TARGET = i686-linux-gnu

TC_CFLAGS =
TC_LDFLAGS =

include ../../mk/spksrc.tc.mk
