SPK_NAME = s3backer
SPK_VERS = 2.0.2
SPK_REV = 1

DEPENDS = cross/s3backer

MAINTAINER = SynoCommunity
DESCRIPTION = FUSE-based single file backing store via Amazon S3.
CHANGELOG = "Initial diyspk package release."
DISPLAY_NAME = s3backer

HOMEPAGE = https://github.com/archiecobbs/s3backer/wiki/ManPage
LICENSE  = GPLv2

STARTABLE = no
SPK_COMMANDS = bin/s3backer

include ../../mk/spksrc.spk.mk
