TC_ARCH = 88f6281
TC_VERS = 5.0
TC_KERNEL = 2.6.32
TC_GCC = 4.6.4
TC_GLIBC = 2.15

TC_DIST = gcc464_glibc215_88f6281-GPL
TC_EXT = tgz
TC_DIST_SITE_PATH = Marvell%2088F628x%20Linux%202.6.32

TC_TARGET = arm-marvell-linux-gnueabi
TC_SYSROOT = $(TC_TARGET)/libc
TC_LIBRARY = $(TC_SYSROOT)/usr/lib

include ../../mk/spksrc.tc.mk
