PKG_NAME = giflib
PKG_VERS = 5.1.2
PKG_EXT = tar.bz2
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)
PKG_DIST_NAME = $(PKG_DIR).$(PKG_EXT)
PKG_DIST_SITE = http://downloads.sourceforge.net/project/$(PKG_NAME)

DEPENDS =

HOMEPAGE = http://sourceforge.net/projects/giflib
COMMENT  = A library for processing GIFs
LICENSE  = MIT License

GNU_CONFIGURE = 1

include ../../mk/spksrc.cross-cc.mk

