PKG_NAME = utf8proc
PKG_VERS = 2.11.0
PKG_EXT = tar.gz
PKG_DIST_NAME = v$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = https://github.com/JuliaStrings/utf8proc/archive/refs/tags
PKG_DIST_FILE = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS =

HOMEPAGE = https://github.com/JuliaStrings/utf8proc
COMMENT = utf8proc is a small, clean C library for Unicode normalization, case-folding, and other transformations
LICENSE = MIT

include ../../mk/spksrc.cross-cmake.mk
