PKG_NAME = mercurial
PKG_VERS = 3.6.1
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = http://mercurial.selenic.com/release
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS = cross/docutils

HOMEPAGE = http://mercurial.selenic.com/
COMMENT  = Mercurial is a free, distributed source control management tool
LICENSE  = GPLv2

include ../../mk/spksrc.python-wheel.mk
