PKG_NAME = mercurial
PKG_VERS = 4.8.1
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = https://www.mercurial-scm.org/release
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS =

HOMEPAGE = https://www.mercurial-scm.org
COMMENT  = Mercurial is a free, distributed source control management tool
LICENSE  = GPLv2

include ../../mk/spksrc.python-wheel.mk
