SPK_NAME = netcat
SPK_VERS = 0.7.1
SPK_REV = 1

DEPENDS = cross/netcat

MAINTAINER = SynoCommunity
DESCRIPTION = Netcat is a featured networking utility which reads and writes data across network connections, using the TCP/IP protocol.
DISPLAY_NAME = netcat
STARTABLE = no

HOMEPAGE = https://netcat.sourceforge.net/
LICENSE = GPLv2

SPK_COMMANDS = bin/nc bin/netcat

include ../../mk/spksrc.spk.mk
