PKG_NAME = libiconv
PKG_VERS = 1.15
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = http://ftp.gnu.org/pub/gnu/$(PKG_NAME)
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS =

HOMEPAGE = https://www.gnu.org/software/libiconv
COMMENT  = iconv implementation
LICENSE  = GNU GPLv3

GNU_CONFIGURE = 1

include ../../mk/spksrc.cross-cc.mk
