SPK_NAME = dua
SPK_VERS = 2.17.2
SPK_REV = 1

DEPENDS = cross/$(SPK_NAME)

UNSUPPORTED_ARCHS = $(OLD_PPC_ARCHS)

MAINTAINER = SynoCommunity
DESCRIPTION = A tool to conveniently learn about the disk usage of directories, fast!
DISPLAY_NAME = $(SPK_NAME)
STARTABLE = no

HOMEPAGE = https://lib.rs/crates/dua-cli
LICENSE  = MIT

SPK_COMMANDS = bin/dua

include ../../mk/spksrc.spk.mk
