PKG_NAME = msgpack-python
PKG_VERS = 0.4.6
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = https://files.pythonhosted.org/packages/source/m/$(PKG_NAME)
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS =

HOMEPAGE = http://msgpack.org/
COMMENT  = It\'s like JSON. but fast and small.
LICENSE  = Apache

include ../../mk/spksrc.python-wheel.mk
