ADGUARDHOME="${SYNOPKG_PKGDEST}/bin/adguardhome"
CFG_FILE="${SYNOPKG_PKGVAR}/AdGuardHome.yml"
PID_FILE="${SYNOPKG_PKGVAR}/adguardhome.pid"
WEB_UI="0.0.0.0:${SYNOPKG_PKGPORT}"
SERVICE_COMMAND="${ADGUARDHOME} --web-addr ${WEB_UI} -c ${CFG_FILE} --pidfile ${PID_FILE} -l ${LOG_FILE} --work-dir ${SYNOPKG_PKGVAR}"
SVC_BACKGROUND=y