SPK_NAME = inotify-tools
SPK_VERS = 3.20.2.2
SPK_REV = 1
SPK_ICON = src/$(SPK_NAME).png

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = cyc1ingsir
DESCRIPTION = inotify-tools is a C library and a set of command-line programs for Linux providing a simple interface to inotify.
RELOAD_UI = no
DISPLAY_NAME = inotify-tools
STARTABLE = no

CHANGELOG = "Initial release"

HOMEPAGE = https://github.com/inotify-tools/inotify-tools/
LICENSE  = GPLv2

SPK_COMMANDS=bin/inotifywait bin/inotifywatch


include ../../mk/spksrc.spk.mk
