TC_ARCH = armadaxp
TC_VERS = 7.1
TC_KERNEL = 3.2.101
TC_GLIBC = 2.26

TC_DIST = armadaxp-gcc850_glibc226_hard-GPL
TC_DIST_SITE_PATH = Marvell%20Armada%20XP%20Linux%203.2.101

TC_TARGET = arm-unknown-linux-gnueabi
TC_SYSROOT = $(TC_TARGET)/sysroot
TC_EXTRA_CFLAGS = -mhard-float -mfpu=vfpv3-d16

include ../../mk/spksrc.tc.mk
