TC_ARCH = armadaxp
TC_VERS = 6.2.2
TC_KERNEL = 3.2.40
TC_GCC = 4.9.3
TC_GLIBC = 2.20

TC_DIST = armadaxp-gcc493_glibc220_hard-GPL
TC_DIST_SITE_PATH = Marvell%20Armada%20XP%20Linux%203.2.40

TC_TARGET = arm-unknown-linux-gnueabi
TC_SYSROOT = $(TC_TARGET)/sysroot
TC_EXTRA_CFLAGS = -mhard-float -mfpu=vfpv3-d16

include ../../mk/spksrc.tc.mk
