SPK_NAME = mosh
SPK_VERS = 1.4.0
SPK_REV = 3
SPK_ICON = src/mosh.png

DEPENDS = cross/$(SPK_NAME)

SPK_DEPENDS = "Perl>=5.14"

MAINTAINER = SynoCommunity
DESCRIPTION = mosh, the mobile shell is a remote terminal application that allows roaming, supports intermittent connectivity, and provides intelligent local echo and line editing of user keystrokes. Mosh is a replacement for interactive SSH terminals. It's more robust and responsive, especially over Wi-Fi, cellular, and long-distance links.

DISPLAY_NAME = mosh
STARTABLE = no
CHANGELOG = "1. Update Mosh to version 1.4.0.<br/>2. Update openssl to 1.1.1t."

HOMEPAGE = https://mosh.org
LICENSE  = GPLv3+

SPK_COMMANDS = bin/mosh bin/mosh-client bin/mosh-server

include ../../mk/spksrc.spk.mk
