SPK_NAME = mosh
SPK_VERS = 1.3.2
SPK_REV = 1
SPK_ICON = src/mosh.png

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = SynoCommunity
DESCRIPTION = Mosh: the mobile shell
DISPLAY_NAME = mosh
STARTABLE = no

HOMEPAGE = https://mosh.org
LICENSE  = GPLv3+

SPK_COMMANDS = bin/mosh bin/mosh-client bin/mosh-server

include ../../mk/spksrc.spk.mk
