SPK_NAME = php
SPK_VERS = 7.3.33
SPK_REV = 1
SPK_ICON = src/php.png

DEPENDS = cross/php-7.3

#UNSUPPORTED_ARCHS = $(OLD_PPC_ARCHS) $(ARMv5_ARCHS)

MAINTAINER = SynoCommunity
DESCRIPTION = PHP is a popular general-purpose scripting language that is especially suited to web development.
STARTABLE = no
DISPLAY_NAME = PHP 7.3
CHANGELOG = "1. Initial SynoCommunity release"

HOMEPAGE = https://www.php.net/
LICENSE  = PHP License, version 3.01

# add links for tools
SPK_COMMANDS  = bin/php
SPK_COMMANDS += bin/php-cgi
SPK_COMMANDS += bin/php-config
SPK_COMMANDS += bin/phpdbg
SPK_COMMANDS += bin/phpize
SPK_COMMANDS += bin/pear
SPK_COMMANDS += bin/peardev
SPK_COMMANDS += bin/pecl
SPK_COMMANDS += bin/phar

include ../../mk/spksrc.spk.mk
