PKG_NAME = libexif
PKG_VERS = 0.6.25
PKG_EXT = tar.xz
PKG_DIST_NAME = libexif-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = https://github.com/libexif/libexif/releases/download/v$(PKG_VERS)
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS =

HOMEPAGE = https://github.com/libexif/libexif
COMMENT  = libexif is a library for parsing, editing, and saving EXIF data.
LICENSE  = LGPLv2

GNU_CONFIGURE = 1

include ../../mk/spksrc.cross-cc.mk
