PKG_NAME = libuuid
PKG_VERS = 1.0.3
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = https://downloads.sourceforge.net/project/$(PKG_NAME)
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS =

HOMEPAGE = http://sourceforge.net/projects/libuuid/
COMMENT  = Portable uuid C library

GNU_CONFIGURE = 1

include ../../mk/spksrc.cross-cc.mk
