DDNS_GO="${SYNOPKG_PKGDEST}/bin/ddns-go -l :9876 -f 60 -cacheTimes 1800"
CONFIG_FILE="${SYNOPKG_PKGVAR}/config.yaml"

SERVICE_COMMAND="${DDNS_GO} -c ${CONFIG_FILE}"
SVC_BACKGROUND=yes
SVC_WRITE_PID=yes
