SPK_NAME = davfs2
SPK_VERS = 1.6.0
SPK_REV = 2
SPK_ICON = src/davfs2.png

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = SynoCommunity
DESCRIPTION = Mount a WebDAV resource as a regular file system.
RELOAD_UI = no
DISPLAY_NAME = davfs2
STARTABLE = no

HOMEPAGE = http://savannah.nongnu.org/projects/davfs2
LICENSE = GPLv3+

SPK_COMMANDS = sbin/mount.davfs sbin/umount.davfs

include ../../mk/spksrc.spk.mk
