
PKG_NAME = pyalsa
PKG_VERS = 1.0.24
PKG_EXT = tar.bz2
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = ftp://ftp.alsa-project.org/pub/pyalsa

DEPENDS = cross/alsa-lib cross/setuptools

MAINTAINER = http://packages.nas-forum.com
HOMEPAGE   = http://www.alsa-project.org/
COMMENT    = Advanced Linux Sound Architecture provides audio and MIDI functionality to the Linux operating system
LICENSE    =

ADDITIONAL_CFLAGS =
CONFIGURE_ARGS = 

include ../../mk/spksrc.python-module.mk
