TC_ARCH = x86
TC_VERS = 6.0.2
TC_KERNEL = 3.10.77
TC_GCC = 4.9.3
TC_GLIBC = 2.20

TC_DIST = x64-gcc493_glibc220_linaro_x86_64-GPL
TC_DIST_SITE_PATH = Intel%20x86%20Linux%203.10.77%20%28Pineview%29

TC_TARGET = x86_64-pc-linux-gnu
TC_SYSROOT = $(TC_TARGET)/sys-root

include ../../mk/spksrc.tc.mk
