TC_ARCH = rtd1296
TC_VERS = 7.2
TC_KERNEL = 4.4.302
TC_GLIBC = 2.36

TC_DIST = rtd1296-gcc1220_glibc236_armv8-GPL
TC_DIST_SITE_PATH = Realtek%20RTD129x%20Linux%204.4.302

TC_TARGET = aarch64-unknown-linux-gnu
TC_SYSROOT = $(TC_TARGET)/sysroot

include ../../mk/spksrc.tc.mk
