SPK_NAME = helix
SPK_VERS = 24.07
SPK_REV = 1
SPK_ICON = src/helix.png

DEPENDS = cross/helix

MAINTAINER = SynoCommunity
DESCRIPTION = A post-modern modal text editor.
DISPLAY_NAME = helix
STARTABLE = no
CHANGELOG = "Initial package"

HOMEPAGE = https://helix-editor.com/
LICENSE = MPL-2.0
LICENSE_FILE = $(WORK_DIR)/helix-$(SPK_VERS)/LICENSE

SPK_COMMANDS = bin/hx

include ../../mk/spksrc.spk.mk
