SPK_NAME = mediainfo
SPK_VERS = 25.04
SPK_REV = 14
SPK_ICON = src/mediainfo.png

DEPENDS = cross/mediainfo

UNSUPPORTED_ARCHS = $(OLD_PPC_ARCHS) $(ARMv5_ARCHS)

MAINTAINER = ymartin59
DESCRIPTION = "MediaInfo is a convenient unified display of the most relevant technical and tag data for video and audio files."
DISPLAY_NAME = MediaInfo
CHANGELOG = "Update to version 25.04."

HOMEPAGE = https://mediaarea.net/en/MediaInfo
LICENSE = 2-Clause BSD

STARTABLE = no

SPK_COMMANDS = bin/mediainfo

include ../../mk/spksrc.spk.mk
