SPK_NAME = mediainfo
SPK_VERS = 21.03
SPK_REV = 12
SPK_ICON = src/mediainfo.png

DEPENDS  = cross/$(SPK_NAME)

MAINTAINER = ymartin59
DESCRIPTION = "MediaInfo is a convenient unified display of the most relevant technical and tag data for video and audio files."
DISPLAY_NAME = MediaInfo
CHANGELOG = "Update to version 21.03"

HOMEPAGE   = https://mediaarea.net/en/MediaInfo
LICENSE    = 2-Clause BSD

STARTABLE = no

SPK_COMMANDS = bin/mediainfo

include ../../mk/spksrc.spk.mk
