KERNEL_ARCH = geminilakenk
KERNEL_VERS = 7.3
KERNEL_BUILD = 86009
KERNEL_DIST = linux-5.10.x
KERNEL_BASE_ARCH = x86
KERNEL_URL_VERSION = 7.3
# geminilakenk sources are not published but
# configuration do reside in epyc7002 sources
KERNEL_URL_DIR = epyc7002
KERNEL_CONFIG = synology/synoconfigs/geminilakelk5

include ../../mk/spksrc.kernel.mk
