PKG_NAME = libjpeg
PKG_VERS = 09e
PKG_EXT = tar.gz
PKG_DIST_NAME = jpegsrc.v$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = http://jpegclub.org/reference/wp-content/uploads/2022/01
PKG_DIR = jpeg-$(subst 0,,$(PKG_VERS))

DEPENDS =

HOMEPAGE = https://jpegclub.org/reference/reference-sources/
COMMENT  = JPEG library
LICENSE  = Custom BSD-like (free software)

GNU_CONFIGURE = 1

include ../../mk/spksrc.cross-cc.mk
