SPK_NAME = binutils
SPK_VERS = 2.40
SPK_REV = 1

DEPENDS = cross/binutils

MAINTAINER = SynoCommunity
DESCRIPTION = GNU Binutils.
STARTABLE = no

HOMEPAGE = https://www.gnu.org/software/binutils/
LICENSE = GPLv2/LGPLv2

SPK_COMMANDS = bin/strace bin/strace-log-merge

include ../../mk/spksrc.spk.mk
