PKG_NAME = z3
PKG_VERS = 4.11.2
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = https://github.com/Z3Prover/z3/archive/refs/tags
PKG_DIR = $(PKG_NAME)-$(PKG_NAME)-$(PKG_VERS)

HOMEPAGE = https://github.com/Z3Prover/z3
COMMENT  = Theorem prover from Microsoft Research.
LICENSE  = MIT

REQUIRED_MIN_DSM = 7.1

include ../../mk/spksrc.cross-cmake.mk
