SPK_NAME = zstd
SPK_VERS = 1.4.3
SPK_REV = 1
SPK_ICON = src/zstd.png

DEPENDS = cross/zstd

MAINTAINER = stliu
DESCRIPTION = Zstandard is a fast compression algorithm, providing high compression ratios.
DISPLAY_NAME = Zstandard
STARTABLE = no

CHANGELOG = Initial package release

HOMEPAGE = https://facebook.github.io/zstd/
LICENSE  = GPLv2/BSD

SPK_COMMANDS = bin/unzstd bin/zstdcat bin/zstdmt bin/zstd bin/zstdgrep bin/zstdless

include ../../mk/spksrc.spk.mk
