TC_ARCH = bromolow
TC_VERS = 6.2
TC_KERNEL = 3.10.102
TC_GCC = 4.9.3
TC_GLIBC = 2.20

TC_DIST = bromolow-gcc493_glibc220_linaro_x86_64-GPL
TC_DIST_SITE_PATH = Intel%20x86%20linux%203.10.102%20%28Bromolow%29

TC_TARGET = x86_64-pc-linux-gnu
TC_SYSROOT = $(TC_TARGET)/sys-root

include ../../mk/spksrc.tc.mk
