PKG_NAME = libidn
PKG_VERS = 1.27
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = https://ftp.gnu.org/gnu/libidn/
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS = 

HOMEPAGE = https://www.gnu.org/software/libidn/
COMMENT  = Libidn is a package for internationalized string handling based on the Stringprep, Punycode, IDNA and TLD specifications.
LICENSE  = GPLv3

GNU_CONFIGURE = 1

include ../../mk/spksrc.cross-cc.mk
