name: Generate Dependabot Config

on:
  workflow_dispatch:  # allow to manually execute within GitHub
  schedule:
    - cron: '0 2 * * 1'  # Every Monday at 2 AM UTC (optional)
  push:
    paths:
      - 'spk/python*/src/requirements-*.txt'
      - 'native/python*/src/requirements.txt'
      - '.github/actions/generate_dependabot.py'
      - '.github/workflows/generate-dependabot.yml'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyYAML
      
      - name: Run generate_dependabot.py
        run: |
          python .github/actions/generate_dependabot.py
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "🤖 Auto-generate updated dependabot.yml"
          branch: auto/update-dependabot-config
          title: "🤖 Auto-update dependabot.yml"
          body: |
            ## Auto-generated Dependabot Configuration Update
            
            This PR updates the `.github/dependabot.yml` configuration file based on the current Python requirements files found in the repository.
            
            ### Scanned Files
            - `spk/python*/src/requirements-*.txt`
            - `native/python*/src/requirements.txt`
            
            ### Configuration
            - **Schedule**: Weekly updates
            - **Grouping**: All Python dependencies grouped together per package
            
            ---
            *Auto-generated by [generate_dependabot.py](.github/actions/generate_dependabot.py)*
