name: Lint

on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    paths-ignore:
      - "**.md"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Lint
        run: |
          npm install jsonlint
          find spk/ \
           -not -path "*work*" \
           -not -path "spk/transmission/src/settings.json" \
           -regextype posix-extended \
           -regex '.*(\.json|install_uifile\w*|upgrade_uifile\w*|app/config)' \
           | xargs -i node_modules/jsonlint/lib/cli.js -q -c {};
