SPK_NAME = fish
SPK_VERS = 2.2.0
SPK_REV = 1
SPK_ICON = src/ascii_fish.png

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = tmaone
DESCRIPTION = fish is a smart and user-friendly command line shell for OS X, Linux, and the rest of the family.
RELOAD_UI = no
DISPLAY_NAME = fish
STARTABLE = no
CHANGELOG = "initial"

HOMEPAGE   = https://fishshell.com
LICENSE    = GPLv2/mixed

INSTALLER_SCRIPT = src/installer.sh
SSS_SCRIPT       = src/dsm-control.sh
ADDITIONAL_SCRIPTS =

INSTALL_PREFIX = /usr/local/$(SPK_NAME)

include ../../mk/spksrc.spk.mk
