SPK_NAME = micro
SPK_VERS = 2.0.8
SPK_REV = 1
SPK_ICON = src/micro.png

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = SynoCommunity
DESCRIPTION = a modern and intuitive terminal-based text editor
DISPLAY_NAME = micro
STARTABLE = no

HOMEPAGE = https://micro-editor.github.io/
LICENSE  = MIT

SPK_COMMANDS = bin/micro

include ../../mk/spksrc.spk.mk
