SPK_NAME = image-optim
SPK_VERS = 1.0
SPK_REV = 1

DEPENDS = cross/jpegoptim cross/pngcrush cross/advancecomp

MAINTAINER = SynoCommunity
DESCRIPTION = Several utilities for image optimization \(jpegoptim, pngcrush, advancecomp\)
DISPLAY_NAME = Image Optimizers
STARTABLE = no

LICENSE  = GPLv2

SPK_COMMANDS = bin/jpegoptim bin/pngcrush bin/advmng bin/advpng

include ../../mk/spksrc.spk.mk
