SPK_NAME = mc
SPK_VERS = 4.8.23
SPK_REV = 7
SPK_ICON = src/mc.png

DEPENDS = cross/mc

MAINTAINER = SynoCommunity
DESCRIPTION = Midnight Commander is a console application with a text user interface. The main interface consists of two panels which display the file system.
DESCRIPTION_FRE = Midnight Commander est une application en mode texte. L\'interface principale se compose de deux « panneaux » qui affichent les fichiers présents par rapport à leur emplacement sur le disque.
RELOAD_UI = no
DISPLAY_NAME = Midnight Commander
STARTABLE = no
CHANGELOG = "1. Add sftp support<br>2. Fix subshell for /bin/sh as link to /bin/bash<br>3. Fix mouse support<br>4. Fix mcedit, mcview and mcdiff"

HOMEPAGE = http://www.midnight-commander.org
LICENSE  = GNU GPL

SPK_COMMANDS = bin/mc bin/mcdiff bin/mcview bin/mcedit

include ../../mk/spksrc.spk.mk
